//! Single-use OIDC login-state store.
//!
//! Each row corresponds to one in-flight OIDC authorization-code flow initiated
//! by `GET /api/auth/oidc/login`.  The `state` value is the opaque CSPRNG
//! token forwarded to the IdP as `?state=`; it is the primary key and is deleted
//! on first use (`take`) to enforce single-use semantics.
//!
//! Rows expire after 10 minutes (`expires_at`); `take` filters on `expires_at >
//! NOW()` so a replayed or stale state is treated as absent.

use sqlx::PgPool;

/// Persist a new login-state row.
///
/// `state`, `nonce`, and `pkce_verifier` are all base64url-encoded random
/// values generated by `OsRng` in the login-initiation handler.  The 10-minute
/// TTL is enforced by the migration default; `expires_at` is not overridden
/// here.
pub async fn insert(
    pool: &PgPool,
    state: &str,
    nonce: &str,
    pkce_verifier: &str,
) -> Result<(), sqlx::Error> {
    sqlx::query(
        "INSERT INTO oidc_login_states (state, nonce, pkce_verifier) \
         VALUES ($1, $2, $3)",
    )
    .bind(state)
    .bind(nonce)
    .bind(pkce_verifier)
    .execute(pool)
    .await?;
    Ok(())
}

/// Atomically consume a login-state row and return `(nonce, pkce_verifier)`.
///
/// Returns `None` when the row is absent **or** expired (`expires_at <=
/// NOW()`).  The `DELETE … RETURNING` is a single atomic statement: a
/// concurrent second call with the same `state` will find no row and also
/// return `None`, enforcing single-use without a separate SELECT.
// Used by the callback handler in slice 2.
#[allow(dead_code)]
pub async fn take(pool: &PgPool, state: &str) -> Result<Option<(String, String)>, sqlx::Error> {
    let row: Option<(String, String)> = sqlx::query_as(
        "DELETE FROM oidc_login_states \
         WHERE state = $1 AND expires_at > NOW() \
         RETURNING nonce, pkce_verifier",
    )
    .bind(state)
    .fetch_optional(pool)
    .await?;
    Ok(row)
}

/// Best-effort sweep of expired rows.
///
/// Called opportunistically from the login-initiation handler after a
/// successful insert; failures are swallowed (clean-up is not load-bearing).
pub async fn cleanup_expired(pool: &PgPool) -> Result<(), sqlx::Error> {
    sqlx::query("DELETE FROM oidc_login_states WHERE expires_at <= NOW()")
        .execute(pool)
        .await?;
    Ok(())
}

// ─── DB Tests ─────────────────────────────────────────────────────────────────
//
// Run with:
//   RYUKI_DATABASE_URL=postgres://ryuki:ryuki_dev@localhost:5432/ryuki_platform \
//     cargo test -p ryuki-api --bins oidc_login_states_db_tests -- --test-threads=1
//
// Tests SKIP when RYUKI_DATABASE_URL is unset.

#[cfg(test)]
mod oidc_login_states_db_tests {
    use super::*;
    use sqlx::PgPool;

    async fn global_pool() -> Option<PgPool> {
        let url = match std::env::var("RYUKI_DATABASE_URL") {
            Ok(u) if !u.is_empty() => u,
            _ => {
                eprintln!(
                    "oidc_login_states_db_tests: RYUKI_DATABASE_URL not set — skipping DB tests"
                );
                return None;
            }
        };
        let pool = PgPool::connect(&url)
            .await
            .expect("oidc_login_states_db_tests: RYUKI_DATABASE_URL is set but connection failed");
        crate::database::run_migrations(&pool)
            .await
            .expect("migrations must apply cleanly when RYUKI_DATABASE_URL is set");
        Some(pool)
    }

    #[tokio::test]
    async fn test_insert_then_take_returns_nonce_and_pkce() {
        let _serial = crate::database::DB_TEST_SERIAL.lock().await;
        let Some(pool) = global_pool().await else {
            return;
        };

        let state = format!("st-test-{}", uuid::Uuid::new_v4());
        let nonce = "test-nonce-1".to_string();
        let pkce_verifier = "test-pkce-verifier-1".to_string();

        insert(&pool, &state, &nonce, &pkce_verifier)
            .await
            .expect("insert should succeed");

        let result = take(&pool, &state).await.expect("take should not error");
        assert!(result.is_some(), "take should return the row");
        let (got_nonce, got_pkce) = result.unwrap();
        assert_eq!(got_nonce, nonce);
        assert_eq!(got_pkce, pkce_verifier);
    }

    #[tokio::test]
    async fn test_take_is_single_use() {
        let _serial = crate::database::DB_TEST_SERIAL.lock().await;
        let Some(pool) = global_pool().await else {
            return;
        };

        let state = format!("st-su-{}", uuid::Uuid::new_v4());
        insert(&pool, &state, "nonce-su", "pkce-su")
            .await
            .expect("insert");

        let first = take(&pool, &state).await.expect("first take");
        assert!(first.is_some(), "first take should succeed");

        let second = take(&pool, &state).await.expect("second take");
        assert!(
            second.is_none(),
            "second take must return None (single-use)"
        );
    }

    #[tokio::test]
    async fn test_take_expired_row_returns_none() {
        let _serial = crate::database::DB_TEST_SERIAL.lock().await;
        let Some(pool) = global_pool().await else {
            return;
        };

        // Insert a row with an expires_at already in the past.
        let state = format!("st-exp-{}", uuid::Uuid::new_v4());
        sqlx::query(
            "INSERT INTO oidc_login_states (state, nonce, pkce_verifier, expires_at) \
             VALUES ($1, $2, $3, NOW() - INTERVAL '1 second')",
        )
        .bind(&state)
        .bind("nonce-exp")
        .bind("pkce-exp")
        .execute(&pool)
        .await
        .expect("direct insert of expired row");

        let result = take(&pool, &state).await.expect("take of expired row");
        assert!(result.is_none(), "expired row must not be returned by take");

        // Cleanup: remove the expired row we left behind.
        let _ = sqlx::query("DELETE FROM oidc_login_states WHERE state = $1")
            .bind(&state)
            .execute(&pool)
            .await;
    }

    #[tokio::test]
    async fn test_cleanup_expired_removes_old_rows() {
        let _serial = crate::database::DB_TEST_SERIAL.lock().await;
        let Some(pool) = global_pool().await else {
            return;
        };

        let state = format!("st-cl-{}", uuid::Uuid::new_v4());
        sqlx::query(
            "INSERT INTO oidc_login_states (state, nonce, pkce_verifier, expires_at) \
             VALUES ($1, $2, $3, NOW() - INTERVAL '1 hour')",
        )
        .bind(&state)
        .bind("nonce-cl")
        .bind("pkce-cl")
        .execute(&pool)
        .await
        .expect("direct insert of stale row");

        cleanup_expired(&pool).await.expect("cleanup_expired");

        // The row should now be gone.
        let count: (i64,) =
            sqlx::query_as("SELECT COUNT(*) FROM oidc_login_states WHERE state = $1")
                .bind(&state)
                .fetch_one(&pool)
                .await
                .expect("count query");
        assert_eq!(
            count.0, 0,
            "cleanup_expired should have removed the stale row"
        );
    }
}
