apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-ui
  namespace: ryuki-platform
  labels:
    app.kubernetes.io/part-of: ryuki-infrastructure-platform
    app.kubernetes.io/name: portal-ui
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api
  namespace: ryuki-platform
  labels:
    app.kubernetes.io/part-of: ryuki-infrastructure-platform
    app.kubernetes.io/name: platform-api
automountServiceAccountToken: false
