[package]
name = "ryuki-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
ryuki-core = { workspace = true }
serde_yaml = { workspace = true }
figment = { workspace = true }
rayon = "1"
toml = "0.8"
proc-macro2 = { workspace = true }
syn = { workspace = true }
jsonschema = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
ed25519-dalek = { version = "2", features = ["rand_core"] }

[dev-dependencies]
rand = "0.8"
