global:
  enabled: true
  tlsDisable: false

injector:
  enabled: false

server:
  enabled: true
  logLevel: info

  standalone:
    enabled: false

  serviceAccount:
    create: true
    name: vault

  dataStorage:
    enabled: true
    size: 50Gi
    storageClass: ""
    accessMode: ReadWriteOnce
    mountPath: /vault/data

  auditStorage:
    enabled: true
    size: 20Gi
    storageClass: ""
    accessMode: ReadWriteOnce
    mountPath: /vault/audit

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  extraVolumes:
    - type: secret
      name: vault-server-tls

  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1

  networkPolicy:
    enabled: true

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: vault
              component: server
          topologyKey: kubernetes.io/hostname

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = 0
          tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
          tls_key_file = "/vault/userconfig/vault-server-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/ca.crt"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

ui:
  enabled: true
  serviceType: ClusterIP
