#!/usr/bin/env python3
"""Render docs/*.md to themed HTML pages served on ryuki.io.

GitHub Pages deploys the docs/ folder as-is (no Jekyll — the site is
uploaded by .github/workflows/static.yml), so the markdown sources are
pre-rendered here. Run from the repo root after editing any docs/*.md:

    python3 scripts/md2docs.py

Outputs one <name>.html per markdown file plus documentation.html (the
index). The markdown files stay the source of truth and keep working on
GitHub's web UI; links to docs/<name>.md are rewritten to <name>.html.

When docs/api/api-doc.json exists (see --api-doc to point elsewhere), the
API reference is rendered from it instead of docs/api/endpoints.md: the
api-reference page becomes a hub and one docs/api-<area>.html page is
generated per area. Without it, the legacy markdown rendering is kept.
"""
import argparse
import html as html_mod
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"

PAGES = [
    ("getting-started", "Getting Started",
     "Prerequisites, database setup, first build and run."),
    ("first-test", "First Test Acceptance",
     "Normative dry-run and live vSphere test gates, evidence, and cleanup."),
    ("architecture", "Architecture",
     "The stack, component diagram, key decisions and network policy."),
    ("configuration", "Configuration",
     "Environment variables, providers and platform configuration."),
    ("entra-app-registration", "Entra App Registration",
     "OIDC / OAuth2 app registration and role setup for Entra ID."),
    ("site-management", "Site Management",
     "UN/LOCODE locations, activation and the admin API."),
    ("rbac-and-scoping", "RBAC & Scoping",
     "Roles, route access classes, site/environment scopes and their enforcement semantics."),
    ("agents-and-live-execution", "Agents & Live Execution",
     "Enrolling execution agents and the signed approval chain that gates a live apply."),
    ("orchestration", "Multi-Step Orchestration",
     "Dependency-ordered step plans, per-step live approval, and automatic teardown."),
    ("notifications", "Notifications",
     "In-app notifications, read receipts, the portal bell, and what emits them."),
    ("using-the-api", "Using the API",
     "Authentication, conventions, and a complete request lifecycle with curl."),
    ("api-reference", "API Reference",
     "Route-by-area control-plane reference, plus a bounded machine-readable OpenAPI subset."),
]

# Pages whose markdown source lives outside docs/<name>.md.
SOURCE_PATHS = {"api-reference": DOCS / "api" / "endpoints.md"}

# Machine-generated sources get a provenance note instead of an edit link.
GENERATED_NOTE = {
    "api-reference": "Generated by ryuki-validator from the API route registrations.",
}

# ── API reference (docs/api/api-doc.json) ───────────────────────
API_HUB = "api-reference"          # PAGES entry that becomes the hub
API_DOC_DEFAULT = DOCS / "api" / "api-doc.json"
OPENAPI_SRC = DOCS / "api" / "openapi.json"
GENERATED_API_NOTE = "Generated from the API route registrations."
API_HUB_SECTIONS = [("conventions", "Conventions"), ("areas", "Areas")]

# Conventions strip: (label, one-liner, guide anchor or None). The links
# point INTO the guides instead of duplicating them.
API_CONVENTIONS = [
    ("Authentication",
     "Sessions or API bearer tokens; four auth modes.",
     "/rbac-and-scoping.html#authentication-modes"),
    ("Access & permissions",
     "Human routes use `admin`, `approve`, `execute`, `request`, `audit`, or `read`; `public`, `agent`, and `webhook` use distinct credentials.",
     "/rbac-and-scoping.html#route-access-classes"),
    ("Scoping",
     "Site and environment scopes narrow what a principal sees and touches.",
     "/rbac-and-scoping.html#scopes"),
    ("Pagination",
     "List routes document their own offset or cursor pagination contract.",
     "/using-the-api.html#pagination"),
    ("Errors",
     "Out-of-scope reads return `404`; explicit cross-scope writes return `403`.",
     "/rbac-and-scoping.html#enforcement-semantics"),
]


def source_for(name: str) -> Path:
    return SOURCE_PATHS.get(name, DOCS / f"{name}.md")


def inline(text: str) -> str:
    """Inline markdown -> HTML (escape first, then spans)."""
    out = html_mod.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)

    def link(m):
        label, url = m.group(1), m.group(2)
        url = re.sub(r"^(?:docs/)?([\w-]+)\.md$", r"\1.html", url)
        return f'<a href="{url}">{label}</a>'

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link, out)


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


# ── build-time syntax highlighting (bash / json / env) ──────────
def _esc(s: str) -> str:
    return html_mod.escape(s, quote=False)


_BASH_TOKEN = re.compile(r"""('[^']*'|"[^"]*"|\$\{[^}]*\}|\$\w+|#.*$|\s+|[^\s'"$#]+)""")
_BASH_JOINERS = {"&&", "||", "|", ";"}


def _hl_bash(code: str) -> str:
    out = []
    for ln in code.split("\n"):
        if re.match(r"^\s*#", ln):
            out.append(f'<span class="hl-c">{_esc(ln)}</span>')
            continue
        parts, new_cmd, pos = [], True, 0
        for m in _BASH_TOKEN.finditer(ln):
            if m.start() > pos:
                parts.append(_esc(ln[pos:m.start()]))
            pos = m.end()
            tok = m.group(0)
            if tok.startswith(("'", '"')):
                parts.append(f'<span class="hl-s">{_esc(tok)}</span>')
                new_cmd = False
            elif tok.startswith("$"):
                parts.append(f'<span class="hl-v">{_esc(tok)}</span>')
                new_cmd = False
            elif tok.startswith("#"):
                parts.append(f'<span class="hl-c">{_esc(tok)}</span>')
            elif tok.isspace():
                parts.append(tok)
            else:
                if new_cmd:
                    parts.append(f'<span class="hl-cmd">{_esc(tok)}</span>')
                    new_cmd = False
                elif tok.startswith("-"):
                    parts.append(f'<span class="hl-f">{_esc(tok)}</span>')
                else:
                    parts.append(_esc(tok))
                if tok in _BASH_JOINERS:
                    new_cmd = True
        if pos < len(ln):
            parts.append(_esc(ln[pos:]))
        out.append("".join(parts))
    return "\n".join(out)


_JSON_TOKEN = re.compile(r'("(?:\\.|[^"\\])*")(\s*:)?|(\b(?:true|false|null)\b|-?\d+(?:\.\d+)?)')


def _hl_json(code: str) -> str:
    out, pos = [], 0
    for m in _JSON_TOKEN.finditer(code):
        out.append(_esc(code[pos:m.start()]))
        if m.group(1) and m.group(2):
            out.append(f'<span class="hl-k">{_esc(m.group(1))}</span>{_esc(m.group(2))}')
        elif m.group(1):
            out.append(f'<span class="hl-s">{_esc(m.group(1))}</span>')
        else:
            out.append(f'<span class="hl-n">{_esc(m.group(3))}</span>')
        pos = m.end()
    out.append(_esc(code[pos:]))
    return "".join(out)


def _hl_env(code: str) -> str:
    out = []
    for ln in code.split("\n"):
        if re.match(r"^\s*#", ln):
            out.append(f'<span class="hl-c">{_esc(ln)}</span>')
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)(=)(.*)$", ln)
        if m:
            val = m.group(3)
            val_html = (f'<span class="hl-s">{_esc(val)}</span>'
                        if val.startswith(("'", '"')) else _esc(val))
            out.append(f'<span class="hl-v">{_esc(m.group(1))}</span>={val_html}')
        else:
            out.append(_esc(ln))
    return "\n".join(out)


def highlight(code: str, lang: str) -> str:
    if lang == "bash":
        return _hl_bash(code)
    if lang == "json":
        return _hl_json(code)
    if lang == "env":
        return _hl_env(code)
    return _esc(code)


def convert(md: str) -> str:
    lines = md.splitlines()
    out, i = [], 0
    in_ul = in_ol = False

    def close_lists():
        nonlocal in_ul, in_ol
        if in_ul:
            out.append("</ul>")
            in_ul = False
        if in_ol:
            out.append("</ol>")
            in_ol = False

    while i < len(lines):
        line = lines[i]

        if line.startswith("```"):
            close_lists()
            lang = line[3:].strip()
            block = []
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                block.append(lines[i])
                i += 1
            i += 1
            cls = f' class="lang-{lang}"' if lang else ""
            out.append(f"<pre><code{cls}>{highlight(chr(10).join(block), lang)}</code></pre>")
            continue

        if line.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[\s:|-]+\|$", lines[i + 1]):
            close_lists()
            cells = [c.strip() for c in line.strip("|").split("|")]
            out.append("<table><thead><tr>" +
                       "".join(f"<th>{inline(c)}</th>" for c in cells) +
                       "</tr></thead><tbody>")
            i += 2
            while i < len(lines) and lines[i].startswith("|"):
                cells = [c.strip() for c in lines[i].strip("|").split("|")]
                out.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in cells) + "</tr>")
                i += 1
            out.append("</tbody></table>")
            continue

        m = re.match(r"^(#{1,4})\s+(.*)$", line)
        if m:
            close_lists()
            level = len(m.group(1))
            text = m.group(2)
            out.append(f'<h{level} id="{slug(text)}">{inline(text)}</h{level}>')
            i += 1
            continue

        if re.match(r"^\s*-\s+", line):
            if not in_ul:
                close_lists()
                out.append("<ul>")
                in_ul = True
            out.append(f"<li>{inline(re.sub(r'^\s*-\s+', '', line, count=1))}</li>")
            i += 1
            continue

        if re.match(r"^\s*\d+\.\s+", line):
            if not in_ol:
                close_lists()
                out.append("<ol>")
                in_ol = True
            out.append(f"<li>{inline(re.sub(r'^\s*\d+\.\s+', '', line, count=1))}</li>")
            i += 1
            continue

        if not line.strip():
            close_lists()
            i += 1
            continue

        close_lists()
        para = [line]
        while i + 1 < len(lines) and lines[i + 1].strip() and not re.match(
                r"^(#{1,4}\s|```|\||\s*-\s|\s*\d+\.\s)", lines[i + 1]):
            i += 1
            para.append(lines[i])
        out.append(f"<p>{inline(' '.join(para))}</p>")
        i += 1

    close_lists()
    return "\n".join(out)


DOCS_CSS = r"""
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
:root{
  --font:'Inter',system-ui,sans-serif;
  --mono:'JetBrains Mono',ui-monospace,monospace;
  --radius:10px;--transition:220ms ease;
}
:root{
  --bg:#0b0d12;--bg-secondary:#11141b;--text:#e7eaf1;--text-secondary:#9aa2b2;
  --border:#222734;--border-strong:#313848;
  --accent:#e25d5d;--accent-bg:#3a1313;--logo-red:#c0392b;--logo-gold:#FFD700;
  --code-bg:#0d1119;--code-text:#d6deeb;--inline-code:#1c1517;
  --header-bg:rgba(11,13,18,.86);
}
@media (prefers-reduced-motion: no-preference){html{scroll-behavior:smooth}}
body{font-family:var(--font);background:var(--bg);color:var(--text);
  transition:background var(--transition),color var(--transition);line-height:1.65}
::selection{background:var(--accent);color:#fff}
.skip-link{position:absolute;left:-9999px;top:0;z-index:30;background:#fff;
  color:#0b0d12;padding:.6rem 1.1rem;border-radius:0 0 8px 0;font-weight:700;text-decoration:none;font-size:.9rem}
.skip-link:focus{left:0}
.site-header{position:sticky;top:0;z-index:10;background:var(--header-bg);
  -webkit-backdrop-filter:blur(14px);backdrop-filter:blur(14px);border-bottom:1px solid var(--border)}
.header-inner{max-width:1140px;margin:0 auto;padding:0 1.5rem;height:58px;
  display:flex;align-items:center;justify-content:space-between;gap:1rem}
.brand{display:flex;align-items:center;gap:.55rem;font-weight:700;font-size:1.08rem;
  letter-spacing:-.02em;color:var(--text);text-decoration:none}
.brand .mark{width:25px;height:25px}
.brand .io{color:var(--accent)}
.header-nav{display:flex;align-items:center;gap:.9rem;font-size:.85rem}
.header-nav a{color:var(--text-secondary);text-decoration:none;font-weight:500}
.header-nav a:hover{color:var(--accent)}
/* ── Docs shell: sticky left nav + content column ── */
.docs-shell{max-width:1140px;margin:0 auto;padding:0 1.5rem;
  display:grid;grid-template-columns:240px minmax(0,1fr);gap:2.8rem;align-items:start}
main{min-width:0;max-width:820px;padding:2.6rem 0 5rem}
.docs-sidebar{position:sticky;top:58px;max-height:calc(100vh - 58px);overflow-y:auto;
  padding:1.9rem 1.2rem 2rem 0;border-right:1px solid var(--border)}
.sb-label{display:block;font-size:.68rem;font-weight:700;text-transform:uppercase;
  letter-spacing:.09em;color:var(--text-secondary);text-decoration:none;margin-bottom:.75rem}
.sb-label:hover{color:var(--accent)}
.sb-label.active{color:var(--accent)}
.sb-filter{width:100%;margin:.1rem 0 .8rem;padding:.42rem .65rem;
  font-family:var(--font);font-size:.8rem;color:var(--text);
  background:var(--bg-secondary);border:1px solid var(--border);border-radius:7px;outline:none}
.sb-filter:focus{border-color:var(--accent)}
.sb-empty{display:none;font-size:.78rem;color:var(--text-secondary);padding:.2rem .65rem}
.sb-results{margin:0 0 .6rem}
.sb-results a{display:block;padding:.45rem .6rem;border:1px solid var(--border);
  border-radius:7px;margin:.35rem 0;text-decoration:none;
  transition:border-color var(--transition),background var(--transition)}
.sb-results a:hover{border-color:var(--accent);background:var(--bg-secondary)}
.sb-results .r-t{font-size:.78rem;font-weight:600;color:var(--text)}
.sb-results .r-t .r-sec{color:var(--accent)}
.sb-results .r-x{font-size:.72rem;line-height:1.45;color:var(--text-secondary);margin-top:.15rem;
  display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}
.sb-results .r-x mark{background:transparent;color:var(--accent);font-weight:700}
.sb-list{list-style:none;margin:0;padding:0}
.sb-list>li{margin:0}
.sb-link{display:block;font-size:.85rem;font-weight:500;color:var(--text-secondary);
  text-decoration:none;padding:.36rem .65rem;border-left:2px solid transparent;
  border-radius:0 6px 6px 0;
  transition:color var(--transition),background var(--transition),border-color var(--transition)}
.sb-link:hover{color:var(--text);background:var(--bg-secondary)}
.sb-link.active{color:var(--accent);font-weight:600;border-left-color:var(--accent);background:var(--accent-bg)}
.sb-sections{list-style:none;margin:.2rem 0 .5rem .65rem;padding:0 0 0 .55rem;
  border-left:1px solid var(--border)}
.sb-sections li{margin:0}
.sb-sections a{display:block;font-size:.78rem;color:var(--text-secondary);text-decoration:none;
  padding:.24rem .55rem;border-radius:5px;
  transition:color var(--transition),background var(--transition)}
.sb-sections a:hover{color:var(--text);background:var(--bg-secondary)}
.sb-sections a.active{color:var(--accent);font-weight:600}
.sb-toggle{display:none}
@media(max-width:940px){
  table{display:block;overflow-x:auto}
  .docs-shell{display:block}
  main{max-width:760px;margin:0 auto;padding:2rem 0 4rem}
  .sb-toggle{display:flex;align-items:center;justify-content:space-between;width:100%;
    background:var(--bg-secondary);border:1px solid var(--border);border-radius:8px;
    font-family:var(--font);font-size:.85rem;font-weight:600;color:var(--text);
    padding:.6rem .9rem;margin-top:1rem;cursor:pointer}
  .sb-toggle svg{width:14px;height:14px;transition:transform .2s ease}
  .sb-toggle[aria-expanded="true"] svg{transform:rotate(180deg)}
  .docs-sidebar{display:none;position:static;max-height:none;border-right:0;
    padding:1rem .2rem .6rem;border-bottom:1px solid var(--border)}
  .docs-sidebar.open{display:block}
}
h1,h2,h3,h4{scroll-margin-top:74px}
.crumb{font-size:.82rem;margin-bottom:1.6rem}
.crumb a{color:var(--accent);text-decoration:none}
.crumb a:hover{text-decoration:underline}
.crumb span{color:var(--text-secondary)}
h1{font-size:2.1rem;letter-spacing:-.02em;margin-bottom:1.2rem}
h2{font-size:1.4rem;letter-spacing:-.01em;margin:2.4rem 0 .8rem;
  padding-top:1.2rem;border-top:1px solid var(--border)}
h3{font-size:1.08rem;margin:1.8rem 0 .6rem}
h4{font-size:.95rem;margin:1.4rem 0 .5rem}
p{margin:.85rem 0;color:var(--text-secondary)}
p strong{color:var(--text)}
li strong{color:var(--text)}
a{color:var(--accent)}
ul,ol{margin:.85rem 0 .85rem 1.4rem;color:var(--text-secondary)}
li{margin:.35rem 0}
code{font-family:var(--mono);font-size:.86em;background:var(--inline-code);
  padding:.12em .38em;border-radius:5px}
pre{background:var(--code-bg);color:var(--code-text);border-radius:var(--radius);
  padding:1.1rem 1.2rem;overflow-x:auto;margin:1rem 0;font-size:.84rem;line-height:1.55}
.pre-wrap{position:relative}
.copy-code{position:absolute;top:.5rem;right:.5rem;
  background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.14);
  color:#aeb7c7;font-family:var(--font);font-size:.68rem;font-weight:600;
  border-radius:6px;padding:.25rem .6rem;cursor:pointer;opacity:0;
  transition:opacity var(--transition),background var(--transition)}
.pre-wrap:hover .copy-code,.copy-code:focus-visible{opacity:1}
@media (hover:none){.copy-code{opacity:1}}
.copy-code:hover{background:rgba(255,255,255,.14);color:#fff}
.copy-code.done{color:#34c98e;border-color:rgba(52,201,142,.4)}
pre code{background:none;padding:0;font-size:1em;color:inherit}
pre .hl-c{color:#637292}
pre .hl-s{color:#e0b46a}
pre .hl-v{color:#ffd966}
pre .hl-cmd{color:#82d9b6}
pre .hl-f{color:#9fb1cd}
pre .hl-k{color:#7da6d9}
pre .hl-n{color:#f78c6c}
table{width:100%;border-collapse:collapse;margin:1rem 0;font-size:.9rem}
th,td{text-align:left;padding:.55rem .8rem;border:1px solid var(--border)}
th{background:var(--bg-secondary)}
td code{white-space:nowrap}
.doc-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));
  gap:1rem;margin-top:1.8rem}
.doc-card{display:block;border:1px solid var(--border);border-radius:var(--radius);
  padding:1.15rem 1.25rem;text-decoration:none;
  transition:border-color var(--transition),background var(--transition)}
.doc-card:hover{border-color:var(--accent);background:var(--accent-bg)}
.doc-card h2{font-size:1.02rem;margin:0 0 .35rem;padding:0;border:0;color:var(--text)}
.doc-card p{font-size:.85rem;margin:0;color:var(--text-secondary)}
.foot-nav{display:flex;justify-content:space-between;gap:1rem;margin-top:3rem;
  padding-top:1.4rem;border-top:1px solid var(--border);font-size:.88rem}
.foot-nav a{text-decoration:none;font-weight:600}
.page-meta{margin-top:3rem;font-size:.78rem;color:var(--text-muted)}
.page-meta a{color:var(--text-secondary);text-decoration:none}
.page-meta a:hover{color:var(--accent)}
.page-meta+.foot-nav{margin-top:1rem}
/* ── API reference: chips, badges, endpoint sections ── */
.method-chip{display:inline-block;font-family:var(--mono);font-size:.62em;font-weight:600;
  line-height:1.5;letter-spacing:.05em;padding:.14em .6em;border-radius:6px;
  border:1px solid var(--border-strong);color:var(--text-secondary);background:var(--bg-secondary)}
.m-get{color:#7da6d9;background:rgba(125,166,217,.12);border-color:rgba(125,166,217,.35)}
.m-post{color:#82d9b6;background:rgba(130,217,182,.12);border-color:rgba(130,217,182,.35)}
.m-put{color:#e0b46a;background:rgba(224,180,106,.12);border-color:rgba(224,180,106,.35)}
.m-patch{color:#f78c6c;background:rgba(247,140,108,.12);border-color:rgba(247,140,108,.35)}
.m-delete{color:var(--accent);background:var(--accent-bg);border-color:rgba(226,93,93,.4)}
.ep-h{display:flex;align-items:center;flex-wrap:wrap;gap:.6rem}
.ep-h code{background:none;padding:0;font-size:.82em;overflow-wrap:anywhere}
.badges{display:flex;flex-wrap:wrap;gap:.45rem;margin:.55rem 0 .9rem}
.badge{display:inline-block;font-size:.72rem;font-weight:600;letter-spacing:.03em;
  padding:.13rem .6rem;border-radius:999px;border:1px solid var(--border-strong);
  color:var(--text-secondary);background:var(--bg-secondary)}
.badge-open{color:#e0b46a;border-color:rgba(224,180,106,.45);background:rgba(224,180,106,.1)}
.ep-summary{color:var(--text);font-weight:500}
.ep-missing{color:var(--text-secondary);font-style:italic}
.ep-doc-heading{color:var(--text);font-weight:600;margin-top:1rem}
.ep-doc-list{margin:.45rem 0 .9rem;padding-left:1.35rem;color:var(--text-secondary)}
.ep-doc-list li+li{margin-top:.28rem}
h3.ep-sub{font-size:.78rem;font-weight:700;text-transform:uppercase;
  letter-spacing:.08em;color:var(--text-secondary);margin:1.5rem 0 .45rem}
.ep-operation{padding-bottom:.35rem}
.ep-operation h4{font-size:.85rem;margin-top:1.15rem}
.ep-note{border-left:3px solid var(--border-strong);padding:.45rem .8rem;
  margin:.7rem 0;color:var(--text-secondary);background:var(--bg-secondary)}
.ep-note code{white-space:normal}
.req{font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.04em}
.req-required{color:#82d9b6}
.req-optional{color:var(--text-secondary)}
.area-count{font-size:.78rem;font-weight:600;text-transform:uppercase;
  letter-spacing:.06em;color:var(--text-secondary)}
.sb-sections a.sb-ep{overflow-wrap:anywhere}
.conv-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));
  gap:.7rem;margin:1.2rem 0}
.conv{border:1px solid var(--border);border-radius:var(--radius);padding:.75rem .85rem}
a.conv{display:block;text-decoration:none;
  transition:border-color var(--transition),background var(--transition)}
a.conv:hover{border-color:var(--accent);background:var(--accent-bg)}
.conv .c-t{display:block;font-size:.85rem;font-weight:700;color:var(--text);margin-bottom:.25rem}
.conv .c-x{display:block;font-size:.78rem;color:var(--text-secondary);line-height:1.5}
.doc-card .rc{margin-top:.55rem;font-size:.7rem;font-weight:600;
  text-transform:uppercase;letter-spacing:.06em;color:var(--text-secondary)}
"""

TEMPLATE = """<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} · Ryuki</title>
<meta name="description" content="{description}">
<link rel="canonical" href="https://ryuki.io/{name}.html">
<meta property="og:type" content="article">
<meta property="og:url" content="https://ryuki.io/{name}.html">
<meta property="og:title" content="{title} · Ryuki">
<meta property="og:description" content="{description}">
<meta property="og:image" content="https://ryuki.io/assets/og.jpg">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.ico" sizes="32x32">
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">
<link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;600&display=swap">
<link rel="stylesheet" href="/assets/docs.css">
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header">
  <div class="header-inner">
    <a href="/" class="brand"><svg class="mark" viewBox="0 0 64 64" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
  <path d="M 35.5 15.3 A 20 20 0 1 0 50.0 26.2" fill="none" stroke="var(--logo-red)" stroke-width="7.5" stroke-linecap="round"/>
  <path d="M 15.5 18.5 L 6.8 19.7 M 8.6 35.0 L 3.3 42.0 M 15.5 51.5 L 16.7 60.2" fill="none" stroke="var(--logo-red)" stroke-width="2.7" stroke-linecap="round"/>
  <path d="M 35.5 15.3 C 31.5 10.8 27.0 9.3 22.5 10.3" fill="none" stroke="var(--logo-red)" stroke-width="3" stroke-linecap="round"/>
  <path d="M 46.5 24.5 L 43 18.5 L 44.5 14 L 40 9 L 46 10.5 L 50.5 4.5 L 51.5 11.5 L 57 13 L 53.5 17.5 L 53.8 22.5 Z" fill="var(--logo-red)"/>
  <circle cx="48.4" cy="13.2" r="1.6" fill="var(--logo-gold)"/>
  <circle cx="32" cy="35" r="5.8" fill="var(--logo-gold)"/>
</svg><span>ryuki<span class="io">.io</span></span></a>
    <nav class="header-nav">
      <a href="/documentation.html">Docs</a>
      <a href="https://github.com/mvandenbulcke/ryuki.io" target="_blank" rel="noopener">GitHub</a>
    </nav>
  </div>
</header>
<div class="docs-shell">
{sidebar}
<main id="main">
{crumb}
{content}
{footnav}
</main>
</div>
<script>
(function(){{
  /* docs sidebar: mobile accordion toggle */
  var tg=document.getElementById('sb-toggle'),sb=document.getElementById('docs-sidebar');
  if(tg&&sb){{
    tg.addEventListener('click',function(){{
      var open=sb.classList.toggle('open');
      tg.setAttribute('aria-expanded',open?'true':'false');
    }});
  }}

  /* docs sidebar: scroll-spy on the current article's sections */
  var secLinks=Array.prototype.slice.call(document.querySelectorAll('.sb-sections a[href^="#"]'));
  if(secLinks.length&&'IntersectionObserver' in window){{
    var byId={{}};
    var targets=[];
    secLinks.forEach(function(l){{
      var id=decodeURIComponent(l.getAttribute('href').slice(1));
      var el=document.getElementById(id);
      if(el){{byId[id]=l;targets.push(el)}}
    }});
    if(targets.length){{
      var spy=new IntersectionObserver(function(entries){{
        entries.forEach(function(en){{
          if(en.isIntersecting){{
            secLinks.forEach(function(l){{l.classList.remove('active')}});
            byId[en.target.id].classList.add('active');
          }}
        }});
      }},{{rootMargin:'-72px 0px -68% 0px',threshold:0}});
      targets.forEach(function(t){{spy.observe(t)}});
    }}
  }}

  /* sidebar: heading filter + lazy full-text search */
  var sbFilter=document.getElementById('sb-filter');
  if(sbFilter){{
    var sbItems=Array.prototype.slice.call(document.querySelectorAll('.sb-list>li'));
    var sbEmpty=document.getElementById('sb-empty');
    var sbResults=document.getElementById('sb-results');
    var listShown=sbItems.length,hitCount=0;
    var sbIndex=null,sbLoading=false,pendingQ=null;
    var updateEmpty=function(q){{
      if(sbEmpty)sbEmpty.style.display=(q&&!listShown&&!hitCount)?'block':'none';
    }};
    var renderHits=function(q){{
      hitCount=0;
      if(!sbResults)return;
      sbResults.textContent='';
      if(!sbIndex||q.length<2)return;
      var scored=[];
      for(var i=0;i<sbIndex.length;i++){{
        var e=sbIndex[i];
        var sc=0;
        if(e.t.toLowerCase().indexOf(q)>-1||(e.s&&e.s.toLowerCase().indexOf(q)>-1))sc=2;
        else if(e.x.indexOf(q)>-1)sc=1;
        if(sc)scored.push([sc,e]);
      }}
      scored.sort(function(a,b){{return b[0]-a[0]}});
      scored.slice(0,8).forEach(function(pair){{
        var e=pair[1];
        var a=document.createElement('a');
        a.href='/'+e.p+(e.a?'#'+e.a:'');
        var tt=document.createElement('div');
        tt.className='r-t';
        tt.textContent=e.t+(e.s?' \u203a ':'');
        if(e.s){{
          var sec=document.createElement('span');
          sec.className='r-sec';
          sec.textContent=e.s;
          tt.appendChild(sec);
        }}
        a.appendChild(tt);
        var ix=e.x.indexOf(q);
        if(ix>-1){{
          var from=Math.max(0,ix-45);
          var pre=(from>0?'\u2026':'')+e.x.slice(from,ix);
          var post=e.x.slice(ix+q.length,ix+q.length+70)+'\u2026';
          var xx=document.createElement('div');
          xx.className='r-x';
          xx.appendChild(document.createTextNode(pre));
          var mk=document.createElement('mark');
          mk.textContent=e.x.slice(ix,ix+q.length);
          xx.appendChild(mk);
          xx.appendChild(document.createTextNode(post));
          a.appendChild(xx);
        }}
        sbResults.appendChild(a);
        hitCount++;
      }});
    }};
    var runSearch=function(q){{
      if(q.length>=2&&!sbIndex&&!sbLoading&&window.fetch){{
        sbLoading=true;pendingQ=q;
        fetch('/search-index.json').then(function(r){{return r.ok?r.json():null}}).then(function(j){{
          if(j){{sbIndex=j;renderHits(pendingQ);updateEmpty(pendingQ)}}
        }}).catch(function(){{}});
      }}
      renderHits(q);
    }};
    sbFilter.addEventListener('input',function(){{
      var q=sbFilter.value.trim().toLowerCase();
      listShown=0;
      sbItems.forEach(function(li){{
        var link=li.querySelector('.sb-link');
        var titleMatch=!q||link.textContent.toLowerCase().indexOf(q)>-1;
        var secEls=li.querySelectorAll('.sb-sections li');
        var any=titleMatch;
        Array.prototype.forEach.call(secEls,function(s){{
          var m=titleMatch||s.textContent.toLowerCase().indexOf(q)>-1;
          s.style.display=m?'':'none';
          if(m)any=true;
        }});
        if(!any&&!secEls.length&&(link.getAttribute('data-sections')||'').indexOf(q)>-1)any=true;
        li.style.display=any?'':'none';
        if(any)listShown++;
      }});
      pendingQ=q;
      runSearch(q);
      updateEmpty(q);
    }});
    sbFilter.addEventListener('keydown',function(e){{
      if(e.key==='Escape'){{
        sbFilter.value='';
        sbFilter.dispatchEvent(new Event('input'));
        sbFilter.blur();
      }}
    }});
    document.addEventListener('keydown',function(e){{
      if(e.key!=='/'||e.metaKey||e.ctrlKey||e.altKey)return;
      var el=document.activeElement;
      if(el&&/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName))return;
      e.preventDefault();
      var sb2=document.getElementById('docs-sidebar');
      var tg2=document.getElementById('sb-toggle');
      if(sb2&&tg2&&getComputedStyle(tg2).display!=='none'&&!sb2.classList.contains('open')){{
        sb2.classList.add('open');
        tg2.setAttribute('aria-expanded','true');
      }}
      sbFilter.focus();
    }});
  }}

  /* copy buttons on code blocks */
  if(navigator.clipboard){{
    Array.prototype.forEach.call(document.querySelectorAll('main pre'),function(pre){{
      var code=pre.textContent;
      var wrap=document.createElement('div');
      wrap.className='pre-wrap';
      pre.parentNode.insertBefore(wrap,pre);
      wrap.appendChild(pre);
      var b=document.createElement('button');
      b.type='button';b.className='copy-code';b.textContent='Copy';
      b.setAttribute('aria-label','Copy code');
      b.addEventListener('click',function(){{
        navigator.clipboard.writeText(code).then(function(){{
          b.textContent='Copied';b.classList.add('done');
          b.setAttribute('aria-label','Copied');
          setTimeout(function(){{
            b.textContent='Copy';b.classList.remove('done');
            b.setAttribute('aria-label','Copy code');
          }},1600);
        }}).catch(function(){{}});
      }});
      wrap.appendChild(b);
    }});
  }}
}})();
</script>
</body>
</html>
"""


def sections(md: str):
    """(slug, title) of every h2 in the markdown, skipping code fences."""
    out, fence = [], False
    for line in md.splitlines():
        if line.startswith("```"):
            fence = not fence
            continue
        if fence:
            continue
        m = re.match(r"^##\s+(.*)$", line)
        if m:
            title = m.group(1).strip()
            out.append((slug(title), title))
    return out


def _plain(md_text: str) -> str:
    """Markdown -> lowercase plain text for the search index."""
    s = re.sub(r"^\s*```.*$", "", md_text, flags=re.M)
    s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)
    s = s.replace("`", "").replace("**", "").replace("|", " ")
    s = re.sub(r"^#{1,6}\s*", "", s, flags=re.M)
    return re.sub(r"\s+", " ", s).strip().lower()


def search_entries(name: str, title: str, md: str):
    """One index entry per h2 section, plus the intro before the first h2."""
    entries, fence = [], False
    cur_title, cur_anchor, buf = "", "", []
    for line in md.splitlines():
        if line.startswith("```"):
            fence = not fence
            buf.append(line)
            continue
        m = None if fence else re.match(r"^##\s+(.*)$", line)
        if m:
            if buf:
                entries.append((cur_title, cur_anchor, _plain("\n".join(buf))))
            cur_title = m.group(1).strip()
            cur_anchor = slug(cur_title)
            buf = []
        else:
            buf.append(line)
    if buf:
        entries.append((cur_title, cur_anchor, _plain("\n".join(buf))))
    return [{"p": f"{name}.html", "t": title, "s": s, "a": a, "x": x}
            for s, a, x in entries if x]


CHEVRON = ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" '
           'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
           '<polyline points="6 9 12 15 18 9"/></svg>')


def build_sidebar(current: str, sections_map: dict) -> str:
    """Left nav pane: every article, the current one expanded with its h2s."""
    items = []
    for name, title, _ in PAGES:
        secs_attr = html_mod.escape(
            "\n".join(s[1].lower() for s in sections_map.get(name, [])), quote=True)
        if name == current:
            sub = ""
            secs = sections_map.get(name, [])
            if secs:
                sub = ('<ul class="sb-sections">'
                       + "".join(f'<li><a href="#{sid}">{html_mod.escape(stitle, quote=False)}</a></li>'
                                 for sid, stitle in secs)
                       + "</ul>")
            items.append(f'<li><a class="sb-link active" aria-current="page" '
                         f'data-sections="{secs_attr}" href="/{name}.html">{title}</a>{sub}</li>')
        else:
            items.append(f'<li><a class="sb-link" data-sections="{secs_attr}" '
                         f'href="/{name}.html">{title}</a></li>')
    overview_cls = " active" if current == "documentation" else ""
    return ('<button class="sb-toggle" id="sb-toggle" aria-expanded="false" '
            f'aria-controls="docs-sidebar">Docs navigation {CHEVRON}</button>\n'
            '<aside class="docs-sidebar" id="docs-sidebar"><nav aria-label="Documentation">'
            f'<a class="sb-label{overview_cls}" href="/documentation.html">Documentation</a>'
            '<input type="search" id="sb-filter" class="sb-filter" placeholder="Search docs ( / )" '
            'aria-label="Search documentation" autocomplete="off">'
            '<div class="sb-results" id="sb-results" role="region" aria-label="Search results"></div>'
            '<ul class="sb-list">' + "".join(items) + "</ul>"
            '<p class="sb-empty" id="sb-empty">No matches.</p></nav></aside>')


def page_meta(name: str, src_path=None, note=None) -> str:
    """Freshness stamp + edit link (or provenance note) for a page.

    The date is the last commit that touched the source, so it only moves
    when the content actually changes (not on regeneration). Generated
    pages pass their own src_path and a provenance note (no edit link).
    """
    src = src_path or source_for(name)
    try:
        rel = src.relative_to(ROOT).as_posix()
    except ValueError:
        rel = ""  # source outside the repo (e.g. --api-doc override)
    date = ""
    if rel:
        date = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", rel],
            capture_output=True, text=True, cwd=ROOT).stdout.strip()
    stamp = f"Last updated {date} · " if date else ""
    if note is None:
        note = GENERATED_NOTE.get(name)
    if note:
        return f'<div class="page-meta">{stamp}{note}</div>'
    edit = f"https://github.com/mvandenbulcke/ryuki.io/edit/main/{rel}"
    return (f'<div class="page-meta">{stamp}'
            f'<a href="{edit}" target="_blank" rel="noopener">Edit this page on GitHub</a></div>')


# ── API reference rendering ─────────────────────────────────────
def load_api_doc(path):
    """Parse the api-doc contract, or None (with a note) when absent."""
    if not path.exists():
        try:
            shown = path.relative_to(ROOT).as_posix()
        except ValueError:
            shown = str(path)
        print(f"note: {shown} not found; skipping API area pages "
              f"(api-reference falls back to docs/api/endpoints.md)")
        return None
    try:
        doc = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        sys.exit(f"error: {path} is not valid JSON: {e}")
    if not isinstance(doc, dict) or not isinstance(doc.get("areas"), list):
        sys.exit(f"error: {path} does not match the api-doc contract (no 'areas' list)")
    return doc


def area_title(area):
    return str(area.get("title") or area.get("key") or "Area")


def area_filename(area):
    name = "api-" + (slug(str(area.get("key") or "")) or "area")
    return name + "-area" if name == API_HUB else name  # never clobber the hub


def endpoint_label(route):
    return f'{(route.get("method") or "?").upper()} {route.get("path") or ""}'.strip()


def area_endpoints(area):
    """[(route, anchor, label)] with per-page unique anchors."""
    seen, out = {}, []
    for route in area.get("routes") or []:
        label = endpoint_label(route)
        base = slug(label) or "endpoint"
        n = seen.get(base, 0) + 1
        seen[base] = n
        out.append((route, base if n == 1 else f"{base}-{n}", label))
    return out


_COMMON_QUERY_DESCRIPTIONS = {
    "limit": "Maximum number of results requested.",
    "offset": "Number of results to skip before returning the page.",
    "q": "Search text used to match results.",
    "sort": "Field or expression used to order results.",
    "direction": "Direction used to order results.",
    "site": "Site identifier used to scope or filter the operation.",
    "environment": "Environment identifier used to scope or filter the operation.",
    "id": "Identifier used to filter the operation.",
}
_COMMON_REQUEST_FIELD_DESCRIPTIONS = {
    "name": "Client-supplied name for the resource or operation.",
    "description": "Client-supplied human-readable description.",
    "reason": "Human-readable reason recorded with the operation and its audit trail.",
    "site": "Site code targeted by the request.",
    "environment": "Environment targeted by the request.",
    "roles": "Application role names assigned by the request.",
    "enabled": "Whether the requested capability should be enabled.",
}
_COMMON_RESPONSE_FIELD_DESCRIPTIONS = {
    "id": "Identifier of the returned resource.",
    "status": "Current operation or resource status.",
    "count": "Number of items represented in this response.",
    "total": "Total number of matching items before the returned page is applied.",
    "limit": "Page-size limit applied to this response.",
    "offset": "Number of matching items skipped before this response page.",
    "items": "Resources returned by this operation.",
    "results": "Results returned by this operation.",
    "created_at": "RFC 3339 timestamp when the resource was created.",
    "updated_at": "RFC 3339 timestamp when the resource was last updated.",
    "expires_at": "RFC 3339 expiry timestamp when one applies.",
    "last_seen_at": "RFC 3339 timestamp of the most recent recorded observation.",
    "request_id": "Request correlation or lifecycle identifier.",
    "error": "Stable machine-readable error code or compact error value.",
    "message": "Human-readable error or result message.",
    "detail": "Optional diagnostic detail safe to return to the caller.",
    "source": "Origin or authority of the returned data.",
}
_UNIVERSAL_RESPONSE_HEADERS = {
    "x-api-version", "x-request-id", "traceresponse",
}
_SIGNIFICANT_OPTIONAL_HEADERS = {
    "idempotency-key", "if-match", "if-none-match", "prefer",
}


def _field_required(field, default=False) -> bool:
    """Read both the new `required` shape and the legacy `optional` shape."""
    if "required" in field:
        return bool(field.get("required"))
    if "optional" in field:
        return not bool(field.get("optional"))
    return default


def _field_description(field, context: str) -> str:
    explicit = str(field.get("description") or field.get("doc") or "").strip()
    if explicit:
        return explicit
    name = str(field.get("name") or "value").strip() or "value"
    low = name.lower()
    semantic = re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower().replace("-", "_")
    if context == "query" and semantic in _COMMON_QUERY_DESCRIPTIONS:
        return _COMMON_QUERY_DESCRIPTIONS[semantic]
    if context == "path":
        if low == "id" or low.endswith("_id"):
            return "Identifier of the target resource in the request path."
        return f"Value of the `{name}` request-path segment."
    if context == "request_header":
        return f"Value supplied in the `{name}` request header."
    if context == "response_header":
        return f"Metadata returned in the `{name}` response header."
    if context == "request_body":
        if semantic in _COMMON_REQUEST_FIELD_DESCRIPTIONS:
            return _COMMON_REQUEST_FIELD_DESCRIPTIONS[semantic]
        return f"Value of `{name}` in the JSON request body."
    if context == "response_body":
        if semantic in _COMMON_RESPONSE_FIELD_DESCRIPTIONS:
            return _COMMON_RESPONSE_FIELD_DESCRIPTIONS[semantic]
        return f"Value of `{name}` returned in the response body."
    return f"Value supplied for the `{name}` query parameter."


def _fields_table(fields, context="query", default_required=False) -> str:
    rows = []
    for field in fields or []:
        if not isinstance(field, dict):
            continue
        name = html_mod.escape(str(field.get("name") or ""), quote=False)
        ty = html_mod.escape(_wire_type(str(field.get("type") or "")), quote=False)
        required = _field_required(field, default=default_required)
        req_label = "Required" if required else "Optional"
        req_class = "required" if required else "optional"
        description = _field_description(field, context)
        rows.append(
            f"<tr><td><code>{name}</code></td><td><code>{ty}</code></td>"
            f'<td><span class="req req-{req_class}">{req_label}</span></td>'
            f"<td>{inline(description)}</td></tr>")
    return ("<table><thead><tr><th>Name</th><th>Type</th><th>Requirement</th>"
            "<th>Description</th></tr></thead><tbody>" + "".join(rows)
            + "</tbody></table>")


def _access_class(route) -> str:
    tier = str(route.get("tier") or route.get("access_class") or "").strip().lower()
    if tier:
        return tier
    return "public" if route.get("auth_exempt") else "authenticated"


def _is_webhook(route) -> bool:
    return _access_class(route) == "webhook"


def _is_public(route) -> bool:
    return bool(route.get("auth_exempt")) or _access_class(route) == "public"


def _interactive_admin_only(route) -> bool:
    return (str(route.get("method") or "").upper() == "POST"
            and str(route.get("path") or "") == "/api/admin/tokens")


def _auth_callback_cookie(route):
    path = str(route.get("path") or "")
    if path == "/api/auth/oidc/callback":
        return "oidc_login_csrf"
    if path == "/api/auth/entra/callback":
        return "entra_login_csrf"
    return None


def _request_body_state(route) -> str:
    state = str(route.get("request_body_state") or "").strip().lower()
    if state in ("json", "none", "unknown", "raw"):
        return state
    if isinstance(route.get("request_body"), dict):
        return "json"
    # Before request_body_state existed, safe HTTP methods were reliably
    # bodyless. A null body on a mutating method was ambiguous and stays so.
    method = str(route.get("method") or "GET").upper()
    return "none" if method in ("GET", "HEAD", "DELETE", "OPTIONS") else "unknown"


def _query_params_state(route) -> str:
    state = str(route.get("query_params_state") or "").strip().lower()
    if state in ("known", "none", "unknown"):
        return state
    # Legacy contracts used null both for no Query extractor and for an
    # unresolved extractor. Preserve honesty: only a concrete list proves the
    # shape was known.
    return "known" if isinstance(route.get("query_params"), list) else "unknown"


def _path_params(route):
    if "path_params" in route:
        value = route.get("path_params")
        return value if isinstance(value, list) else []
    # Backward compatibility for api-doc.json files generated before path
    # extraction was added. Braced names are facts present in the route path.
    names = re.findall(r"\{([^{}]+)\}", str(route.get("path") or ""))
    return [{"name": name, "type": "String", "required": True}
            for name in dict.fromkeys(names)]


def _declared_request_headers(route):
    value = route.get("request_headers")
    return [dict(h) for h in value if isinstance(h, dict)] \
        if isinstance(value, list) else []


def _auth_header(route):
    if _is_public(route) or _is_webhook(route):
        return None
    if _access_class(route) == "agent":
        description = ("Agent bearer credential. Use the enrolled agent token "
                       "whose value starts with `rya_`.")
    else:
        description = "Session or API bearer credential for the calling principal."
    return {"name": "Authorization", "type": "String", "required": True,
            "description": description}


def _effective_request_headers(route):
    """Declared operation headers plus cross-cutting auth/content headers."""
    declared = _declared_request_headers(route)
    by_name = {str(h.get("name") or "").lower(): h for h in declared}
    out, seen = [], set()

    def add(header):
        if not header:
            return
        key = str(header.get("name") or "").lower()
        if not key or key in seen:
            return
        # Public and webhook access classes never get a synthesized or stale
        # bearer header in examples.
        if key == "authorization" and (_is_public(route) or _is_webhook(route)):
            return
        seen.add(key)
        out.append(header)

    add(by_name.get("authorization") or _auth_header(route))
    if _request_body_state(route) == "json":
        add(by_name.get("content-type") or {
            "name": "Content-Type", "type": "String", "required": True,
            "description": "Media type of the JSON request body; use `application/json`.",
        })
    elif "content-type" in by_name:
        add(by_name["content-type"])
    for header in declared:
        add(header)
    add({
        "name": "traceparent", "type": "String", "required": False,
        "description": ("Optional correlation input. When the second dash-separated "
                        "segment has 32 characters, Ryuki reuses it as the request "
                        "correlation identifier; this is not full W3C validation."),
    })
    return out


def _permissions_table(route) -> str:
    access = _access_class(route)
    if _interactive_admin_only(route):
        credential = ("An interactive administrator session or user bearer credential "
                      "is required. Service API tokens (`ryk_...`) are rejected to "
                      "prevent a token from minting another token.")
        scope = "The verified interactive principal must hold the `admin` access class."
    elif _is_webhook(route):
        credential = ("The documented webhook signature header authenticates the "
                      "exact request bytes; no bearer token is used.")
        scope = "The integration identifier in the route selects the receiving scope."
    elif _is_public(route):
        credential = ("No user or agent bearer token is required. Operation-specific "
                      "proof, when present, is documented below.")
        scope = "No authenticated-principal scope is applied to this operation."
    elif access == "agent":
        credential = "An enrolled agent bearer token beginning with `rya_` is required."
        scope = ("The credential represents the enrolled agent; request-path identifiers "
                 "must address that agent's operation.")
    else:
        credential = "An authenticated session or API bearer token is required."
        scope = ("The access class is enforced first; site and environment scopes narrow "
                 "resources on scoped operations.")
    access_html = html_mod.escape(access, quote=False)
    return ("<table><thead><tr><th>Access class</th><th>Credential</th>"
            "<th>Scoping</th></tr></thead><tbody><tr>"
            f"<td><code>{access_html}</code></td><td>{inline(credential)}</td>"
            f"<td>{inline(scope)}</td></tr></tbody></table>")


def _unwrap_rust_type(ty: str) -> str:
    value = (ty or "").strip()
    while True:
        match = re.match(r"^(?:Option|Box|Arc|Rc)<(.*)>$", value)
        if not match:
            return value
        value = match.group(1).strip()


def _split_generic_args(value: str):
    depth, start, args = 0, 0, []
    for index, char in enumerate(value):
        if char == "<":
            depth += 1
        elif char == ">":
            depth = max(0, depth - 1)
        elif char == "," and depth == 0:
            args.append(value[start:index].strip())
            start = index + 1
    args.append(value[start:].strip())
    return args


def _wire_type(ty: str) -> str:
    """Present Rust extraction facts as client-facing JSON wire types."""
    value = _unwrap_rust_type(ty)
    compact = re.sub(r"\s+", "", value)
    low = compact.lower()
    leaf = low.rsplit("::", 1)[-1]
    if leaf in ("string", "str", "&str", "char"):
        return "string"
    if leaf in ("uuid",):
        return "string (uuid)"
    if "datetime<" in low or leaf in ("naivedatetime", "date"):
        return "string (date-time)"
    if leaf in ("bool", "boolean"):
        return "boolean"
    if leaf == "integer" or re.fullmatch(r"[iu](8|16|32|64|128|size)", leaf):
        return "integer"
    if leaf in ("f32", "f64", "number"):
        return "number"
    if leaf in ("object", "array"):
        return leaf
    if low in ("value", "serde_json::value", "jsonvalue"):
        return "JSON value"
    if low in ("null", "()"):
        return "null"

    generic = re.match(r"^(.*)<(.*)>$", value)
    if generic:
        container = generic.group(1).strip().lower().rsplit("::", 1)[-1]
        args = _split_generic_args(generic.group(2))
        if container in ("vec", "vecdeque", "hashset", "btreeset"):
            item = _wire_type(args[0]) if args else "JSON value"
            return f"array<{item}>"
        if container in ("hashmap", "btreemap"):
            mapped = _wire_type(args[1]) if len(args) > 1 else "JSON value"
            return f"object<string, {mapped}>"
        if container in ("result", "cow") and args:
            return _wire_type(args[0])
    if compact.startswith("[") and compact.endswith("]"):
        return "array"
    return f"object ({value})" if value else "JSON value"


def _json_value(ty: str):
    """Return a JSON-serializable, source-safe placeholder for a Rust type."""
    value = _unwrap_rust_type(ty)
    low = re.sub(r"\s+", "", value.lower())
    if low == "bool":
        # Generated examples must never opt into a live/safety-sensitive flag.
        return False
    if re.fullmatch(r"[iu](8|16|32|64|128|size)", low):
        return 0
    if low in ("f32", "f64"):
        return 0.0
    if low in ("string", "str", "&str") or low.endswith("::string"):
        return "<string>"
    if low in ("uuid", "uuid::uuid"):
        return "<uuid>"
    if low.startswith(("vec<", "vecdeque<", "hashset<", "btreeset<")) \
            or (low.startswith("[") and low.endswith("]")):
        return []
    if low.startswith(("hashmap<", "btreemap<")):
        return {}
    if low in ("value", "serde_json::value", "jsonvalue"):
        # `null` is explicitly explained as an unresolved-type placeholder in
        # schematic response bodies; `{}` would falsely assert an object.
        return None
    if low in ("serde_json::map",):
        return {}
    if low in ("()", "null"):
        return None
    # A named type is most safely represented as an object: rendering it as
    # a string would fabricate a wire representation for a nested struct.
    return {}


def _json_object(fields, required_only=False):
    obj = {}
    for field in fields or []:
        if not isinstance(field, dict):
            continue
        if required_only and not _field_required(field, default=True):
            continue
        name = str(field.get("name") or "").strip()
        if name:
            obj[name] = _json_value(str(field.get("type") or ""))
    return obj


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _header_example_value(name: str, route) -> str:
    low = name.lower()
    if low == "authorization":
        return ("Bearer rya_<agent-token>" if _access_class(route) == "agent"
                else "Bearer <token>")
    if low == "content-type":
        return ("application/json" if _request_body_state(route) == "json"
                else "<content-type>")
    if low == "idempotency-key":
        return "<idempotency-key>"
    if low == "x-hub-signature-256":
        return "sha256=<hmac-signature>"
    if low == "x-ryuki-protocol-version":
        return "2"
    if low == "cookie" and _auth_callback_cookie(route):
        return f"{_auth_callback_cookie(route)}=<browser-binding>"
    if "signature" in low:
        return "<signature>"
    if "session" in low:
        return "<session-id>"
    return f"<{slug(name) or 'value'}>"


def _header_in_curl(header, route) -> bool:
    low = str(header.get("name") or "").lower()
    # The human auth contract declares Authorization and the session/CSRF
    # header as optional alternatives. Prefer bearer auth in a standalone
    # example; the session-header flow remains documented in the table.
    if low == "authorization":
        return not (_is_public(route) or _is_webhook(route)
                    or _interactive_admin_only(route))
    if low == "x-ryuki-session-id" and _interactive_admin_only(route):
        return True
    if low == "cookie" and _auth_callback_cookie(route):
        return True
    if _field_required(header):
        return True
    if low in _SIGNIFICANT_OPTIONAL_HEADERS or "signature" in low:
        return True
    return low == "content-type" and _request_body_state(route) in ("json", "raw")


def _example_url(route) -> str:
    path = str(route.get("path") or "/")
    path = re.sub(r"\{([^{}]+)\}", lambda m: f"<{m.group(1)}>", path)
    required_query = [str(field.get("name") or "")
                      for field in (route.get("query_params") or [])
                      if isinstance(field, dict) and _field_required(field)
                      and str(field.get("name") or "")]
    if _auth_callback_cookie(route):
        required_query = list(dict.fromkeys(["code", "state", *required_query]))
    if required_query:
        query = "&".join(f"{name}=<{name}>" for name in required_query)
        path += ("&" if "?" in path else "?") + query
    return f"https://<your-host>{path}"


def curl_example(route) -> str:
    """Build an auth-aware curl request without URL globbing hazards."""
    method = str(route.get("method") or "GET").upper()
    state = _request_body_state(route)
    lines = ["curl --silent --show-error --globoff \\",
             f"  --request {method} \\"]
    for header in _effective_request_headers(route):
        if not _header_in_curl(header, route):
            continue
        name = str(header.get("name") or "")
        value = _header_example_value(name, route)
        lines.append(f"  --header {_shell_quote(f'{name}: {value}')} \\")

    body = route.get("request_body") if isinstance(route.get("request_body"), dict) else {}
    fields = body.get("fields") if isinstance(body.get("fields"), list) else []
    if state == "json":
        if fields:
            payload = json.dumps(_json_object(fields, required_only=True),
                                 separators=(",", ":"), ensure_ascii=False)
            lines.append(f"  --data {_shell_quote(payload)} \\")
        else:
            lines.append("  --data-binary '@request.json' \\")
    elif state == "raw":
        lines.append("  --data-binary '@payload.bin' \\")
    lines.append(f"  {_shell_quote(_example_url(route))}")
    return "\n".join(lines)


def _strip_operation_prefix(text: str, route) -> str:
    text = (text or "").strip()
    method = str(route.get("method") or "").upper()
    path = str(route.get("path") or "")
    if not text or not method or not path:
        return text
    match = re.match(rf"^`?{re.escape(method)}\s+{re.escape(path)}`?", text,
                     flags=re.I)
    if not match:
        return text
    remainder = text[match.end():]
    if not remainder.strip():
        return ""
    separated = re.match(r"^\s*(?:—|–|-|:)\s*(.+)$", remainder, flags=re.S)
    # Some older handler docs put a newline or plain space (rather than an
    # em dash) between the operation and its prose. The exact method/path was
    # still matched above, so stripping it is safe and avoids repeating the
    # HTTP request as the human summary.
    return separated.group(1).strip() if separated else remainder.strip()


def _same_sentence(left: str, right: str) -> bool:
    def normalized(value):
        return re.sub(r"[.!?\s]+$", "", _plain(value)).strip()
    return bool(normalized(left)) and normalized(left) == normalized(right)


def _overview_parts(route):
    """Clean generated operation prefixes and one duplicated first sentence."""
    summary = _strip_operation_prefix(str(route.get("summary") or ""), route)
    if summary and summary[0].isascii() and summary[0].islower():
        summary = summary[0].upper() + summary[1:]
    raw_desc = str(route.get("description") or "").strip()
    blocks = ["\n".join(line.strip() for line in block.strip().splitlines())
              for block in re.split(r"\n\s*\n", raw_desc) if block.strip()]
    if blocks:
        blocks[0] = _strip_operation_prefix(blocks[0], route)
        blocks = [block for block in blocks if block]
        if summary and blocks:
            sentence = re.match(r"^(.+?[.!?])(?:\s+(.*))?$", blocks[0], flags=re.S)
            first = sentence.group(1) if sentence else blocks[0]
            if _same_sentence(summary, first):
                blocks[0] = (sentence.group(2) or "").strip() if sentence else ""
        blocks = [block for block in blocks if block]
    return summary, blocks


def _render_overview_block(block: str) -> list[str]:
    lines = [line.strip() for line in block.splitlines() if line.strip()]
    if not lines:
        return []
    if len(lines) == 1:
        heading = re.match(r"^#{1,4}\s+(.*)$", lines[0])
        if heading:
            return [f'<p class="ep-doc-heading">{inline(heading.group(1))}</p>']
        return [f"<p>{inline(lines[0])}</p>"]

    for pattern, tag in (
        (re.compile(r"^\d+\.\s+(.+)$"), "ol"),
        (re.compile(r"^[-*]\s+(.+)$"), "ul"),
    ):
        first = next((index for index, line in enumerate(lines) if pattern.match(line)), None)
        if first is None or not all(pattern.match(line) for line in lines[first:]):
            continue
        out = []
        if first:
            out.append(f"<p>{inline(' '.join(lines[:first]))}</p>")
        items = "".join(f"<li>{inline(pattern.match(line).group(1))}</li>"
                        for line in lines[first:])
        out.append(f'<{tag} class="ep-doc-list">{items}</{tag}>')
        return out
    return [f"<p>{inline(' '.join(lines))}</p>"]


def _render_request_body(route) -> list[str]:
    state = _request_body_state(route)
    body = route.get("request_body") if isinstance(route.get("request_body"), dict) else {}
    fields = body.get("fields") if isinstance(body.get("fields"), list) else []
    body_type = str(body.get("struct") or body.get("type") or "").strip()
    out = ['<h3 class="ep-sub">Request body</h3>']
    if state == "none":
        out.append("<p>This operation does not accept a request body.</p>")
    elif state == "raw":
        out.append('<p class="ep-note">Supply the required opaque request bytes as-is. '
                   'The exact bytes are covered by <code>X-Hub-Signature-256</code>; '
                   "do not reserialize them after computing the signature.</p>")
    elif state == "unknown":
        out.append('<p class="ep-note">The route contract cannot determine whether this '
                   "operation accepts a request body. Check the handler contract before "
                   "sending one; no body shape is inferred here.</p>")
    else:
        if body_type:
            out.append(f'<p>JSON structure: <code>{html_mod.escape(body_type, quote=False)}</code>.</p>')
        if fields:
            out.append(_fields_table(fields, "request_body", default_required=True))
        else:
            known = (f' The known body type is <code>{html_mod.escape(body_type, quote=False)}</code>.'
                     if body_type else "")
            out.append('<p class="ep-note">This operation accepts JSON, but its field '
                       f"schema is not available.{known} No object shape is fabricated.</p>")
    return out


def _operation_response_headers(response):
    headers = response.get("headers") if isinstance(response, dict) else []
    return [h for h in (headers or []) if isinstance(h, dict)
            and str(h.get("name") or "").lower() not in _UNIVERSAL_RESPONSE_HEADERS]


def _response_body_state(response) -> str:
    state = str(response.get("body_state") or "").strip().lower()
    if state in ("json", "none", "unknown", "raw"):
        return state
    if isinstance(response.get("body"), dict):
        return "json"
    try:
        status = int(response.get("status"))
    except (TypeError, ValueError):
        status = 0
    return "none" if status in (204, 205) or 300 <= status <= 399 else "unknown"


def _render_response(route) -> list[str]:
    out = ['<h3 class="ep-sub">Response</h3>']
    notes = str(route.get("response_notes") or "").strip()
    if "success_responses" not in route:
        if notes:
            out.append(f"<p>{inline(notes)}</p>")
        else:
            out.append('<p class="ep-note">The legacy route contract does not include a '
                       "structured success-response schema.</p>")
        return out

    responses = route.get("success_responses")
    responses = [r for r in responses if isinstance(r, dict)] \
        if isinstance(responses, list) else []
    if not responses:
        out.append('<p class="ep-note">No successful response schema was extracted for '
                   "this operation.</p>")
        if notes:
            out.append(f"<p>{inline(notes)}</p>")
        return out

    rows = []
    for response in responses:
        status = html_mod.escape(str(response.get("status") or "Success"), quote=False)
        description = str(response.get("description") or "Successful response.").strip()
        body = response.get("body")
        body_state = _response_body_state(response)
        if body_state == "none":
            body_label = "No response body"
        elif body_state == "raw":
            body_label = "Raw or text response body"
        elif body_state == "unknown":
            body_label = "Response body schema unavailable"
        elif isinstance(body, dict):
            body_type = str(body.get("type") or "").strip()
            body_label = (f'<code>{html_mod.escape(body_type, quote=False)}</code>'
                          if body_type else "JSON response body")
        else:
            body_label = "Response body schema unavailable"
        rows.append(f"<tr><td><code>{status}</code></td><td>{inline(description)}</td>"
                    f"<td>{body_label}</td></tr>")
    out.append("<table><thead><tr><th>Status</th><th>Description</th><th>Body</th>"
               "</tr></thead><tbody>" + "".join(rows) + "</tbody></table>")

    for response in responses:
        status = html_mod.escape(str(response.get("status") or "Success"), quote=False)
        body = response.get("body")
        body_state = _response_body_state(response)
        if isinstance(body, dict):
            body_type = str(body.get("type") or "").strip()
            fields = body.get("fields") if isinstance(body.get("fields"), list) else []
            if fields:
                out.append(f"<h4><code>{status}</code> response body</h4>")
                if body_type:
                    out.append(f'<p>Structure: <code>{html_mod.escape(body_type, quote=False)}</code>.</p>')
                out.append(_fields_table(fields, "response_body", default_required=True))
            elif body_type:
                out.append(f'<p>For <code>{status}</code>, the known response body type is '
                           f'<code>{html_mod.escape(body_type, quote=False)}</code>. Its '
                           "field schema is unavailable, so no JSON shape is inferred.</p>")
        elif body_state == "raw":
            out.append(f'<p>For <code>{status}</code>, the operation returns a raw or '
                       'text response body; no JSON shape applies.</p>')
        elif body_state == "unknown":
            out.append(f'<p class="ep-note">For <code>{status}</code>, the response '
                       'body could not be resolved from the route contract. It is not '
                       'documented as bodyless.</p>')
        headers = _operation_response_headers(response)
        if headers:
            out.append(f"<h4><code>{status}</code> response headers</h4>")
            out.append(_fields_table(headers, "response_header"))
    if notes and not any(_same_sentence(notes, str(r.get("description") or ""))
                         for r in responses):
        out.append(f"<p>{inline(notes)}</p>")
    return out


def _response_shape_example(route):
    responses = route.get("success_responses")
    if not isinstance(responses, list):
        return None
    for response in responses:
        if not isinstance(response, dict) or not isinstance(response.get("body"), dict):
            continue
        fields = response["body"].get("fields")
        if isinstance(fields, list) and fields:
            status = str(response.get("status") or "Success")
            payload = json.dumps(_json_object(fields), indent=2, ensure_ascii=False)
            return status, payload
    return None


def _render_errors() -> list[str]:
    return [
        '<h3 class="ep-sub">Errors</h3>',
        '<p>JSON failures use one of the platform error envelopes and include the '
        'request correlation metadata when routing reaches the API middleware. See '
        '<a href="/using-the-api.html#errors">Errors</a> for the exact shapes, '
        'authentication failures, retry guidance, and transport-level exceptions.</p>',
    ]


def render_route(route, anchor) -> str:
    method = str(route.get("method") or "?").upper()
    path = str(route.get("path") or "")
    mclass = method.lower()
    if mclass not in ("get", "post", "put", "delete", "patch"):
        mclass = "other"
    out = ['<section class="ep-operation">',
           f'<h2 class="ep-h" id="{anchor}">'
           f'<span class="method-chip m-{mclass}">{html_mod.escape(method, quote=False)}</span>'
           f'<code>{html_mod.escape(path, quote=False)}</code></h2>']
    badges = []
    tier = str(route.get("tier") or "").strip()
    if tier:
        badges.append(f'<span class="badge">{html_mod.escape(tier, quote=False)} access</span>')
    if _is_public(route):
        badges.append('<span class="badge badge-open">no bearer auth required</span>')
    if badges:
        out.append(f'<p class="badges">{"".join(badges)}</p>')

    summary, blocks = _overview_parts(route)
    if summary:
        out.append(f'<p class="ep-summary">{inline(summary)}</p>')
    for para in blocks:
        out.extend(_render_overview_block(para))
    if not summary and not blocks:
        out.append('<p class="ep-missing">No operation description is available yet.</p>')

    out.append('<h3 class="ep-sub">Permissions</h3>')
    out.append(_permissions_table(route))
    out.append('<h3 class="ep-sub">HTTP request</h3>')
    http_request = f"{method} https://<your-host>{path or '/'}"
    out.append(f'<pre><code>{_esc(http_request)}</code></pre>')

    out.append('<h3 class="ep-sub">Path parameters</h3>')
    path_params = _path_params(route)
    if path_params:
        out.append(_fields_table(path_params, "path", default_required=True))
    else:
        out.append("<p>This operation has no path parameters.</p>")

    out.append('<h3 class="ep-sub">Query parameters</h3>')
    query_params = route.get("query_params") or []
    if query_params:
        out.append(_fields_table(query_params, "query"))
    elif _query_params_state(route) == "unknown":
        out.append('<p class="ep-note">This operation accepts query parameters, but '
                   'their field schema could not be extracted. No parameter list is '
                   'inferred here.</p>')
    else:
        out.append("<p>This operation has no query parameters.</p>")

    out.append('<h3 class="ep-sub">Request headers</h3>')
    request_headers = _effective_request_headers(route)
    if request_headers:
        out.append(_fields_table(request_headers, "request_header"))
    else:
        out.append("<p>No operation-specific request headers are required.</p>")

    out.extend(_render_request_body(route))
    out.extend(_render_response(route))
    out.extend(_render_errors())

    out.append('<h3 class="ep-sub">Examples</h3>')
    out.append("<h4>Request</h4>")
    out.append(f'<pre><code class="lang-bash">{_hl_bash(curl_example(route))}</code></pre>')
    response_example = _response_shape_example(route)
    if response_example:
        status, payload = response_example
        out.append("<h4>Schematic response body</h4>")
        out.append('<p class="ep-note">Illustrative shape generated from the extracted '
                   'field types, not a recorded live response. Values are placeholders; '
                   '<code>null</code> marks a field whose type could not be resolved.</p>')
        out.append(f'<p>Success status: <code>{html_mod.escape(status, quote=False)}</code></p>')
        out.append(f'<pre><code class="lang-json">{_hl_json(payload)}</code></pre>')
    out.append("</section>")
    return "\n".join(out)


def api_area_content(area) -> str:
    title = area_title(area)
    eps = area_endpoints(area)
    out = [f"<h1>{html_mod.escape(title, quote=False)} API</h1>"]
    desc = str(area.get("description") or "").strip()
    if desc:
        out.append(f"<p>{inline(desc)}</p>")
    n = len(eps)
    out.append(f'<p class="area-count">{n} route{"s" if n != 1 else ""}</p>')
    out.append('<p class="ep-note"><strong>Response metadata:</strong> '
               '<code>x-api-version</code>, <code>x-request-id</code>, and '
               '<code>traceresponse</code> apply to normal routed responses and are omitted '
               'from the per-operation header tables below.</p>')
    if not eps:
        out.append('<p class="ep-missing">No routes extracted for this area yet.</p>')
    for route, anchor, _ in eps:
        out.append(render_route(route, anchor))
    return "\n".join(out)


def build_api_sidebar(api, current_fname) -> str:
    """Dedicated left nav for area pages: all areas, current one expanded
    with a link per endpoint. Reuses the docs-sidebar markup so the mobile
    toggle, filter, and scroll-spy in TEMPLATE keep working."""
    items = []
    for area in api.get("areas") or []:
        fname = area_filename(area)
        title = html_mod.escape(area_title(area), quote=False)
        if fname == current_fname:
            sub = ""
            eps = area_endpoints(area)
            if eps:
                sub = ('<ul class="sb-sections">'
                       + "".join(f'<li><a class="sb-ep" href="#{anchor}">'
                                 f'{html_mod.escape(label, quote=False)}</a></li>'
                                 for _, anchor, label in eps)
                       + "</ul>")
            items.append(f'<li><a class="sb-link active" aria-current="page" '
                         f'href="/{fname}.html">{title}</a>{sub}</li>')
        else:
            items.append(f'<li><a class="sb-link" href="/{fname}.html">{title}</a></li>')
    return ('<button class="sb-toggle" id="sb-toggle" aria-expanded="false" '
            f'aria-controls="docs-sidebar">Docs navigation {CHEVRON}</button>\n'
            '<aside class="docs-sidebar" id="docs-sidebar"><nav aria-label="API reference">'
            '<a class="sb-label" href="/documentation.html">Documentation</a>'
            '<input type="search" id="sb-filter" class="sb-filter" placeholder="Search docs ( / )" '
            'aria-label="Search documentation" autocomplete="off">'
            '<div class="sb-results" id="sb-results" role="region" aria-label="Search results"></div>'
            f'<a class="sb-label" href="/{API_HUB}.html">API Reference</a>'
            '<ul class="sb-list">' + "".join(items) + "</ul>"
            '<p class="sb-empty" id="sb-empty">No matches.</p></nav></aside>')


def api_hub_content(api, openapi_available) -> str:
    areas = api.get("areas") or []
    total = sum(len(a.get("routes") or []) for a in areas)
    tiles = []
    for label, text, href in API_CONVENTIONS:
        inner = (f'<span class="c-t">{html_mod.escape(label, quote=False)}</span>'
                 f'<span class="c-x">{inline(text)}</span>')
        tiles.append(f'<a class="conv" href="{href}">{inner}</a>' if href
                     else f'<div class="conv">{inner}</div>')
    cards = []
    for area in areas:
        fname = area_filename(area)
        t = html_mod.escape(area_title(area), quote=False)
        n = len(area.get("routes") or [])
        cards.append(f'<a class="doc-card" href="/{fname}.html"><h2>{t}</h2>'
                     f'<p>{inline(str(area.get("description") or "").strip())}</p>'
                     f'<p class="rc">{n} route{"s" if n != 1 else ""}</p></a>')
    openapi_p = ""
    if openapi_available:
        openapi_p = ('<p>Machine-readable spec: <a href="/openapi.json">'
                     '<code>openapi.json</code></a>. It covers the bounded agent, '
                     'public, and operations-read subset for tooling; it is not a '
                     'schema for the full route-by-area surface documented on these '
                     'pages.</p>')
    return (
        "<h1>API Reference</h1>"
        f"<p>The control plane serves <strong>{total} routes</strong> across "
        f"<strong>{len(areas)} areas</strong>. Most routes require an authenticated "
        "session or API bearer token; agent and webhook routes use their documented "
        "protocol credentials, while a small bootstrap set is public. Pick an area below, or start "
        "with the conventions that apply everywhere.</p>"
        '<h2 id="conventions">Conventions</h2>'
        "<p>These rules hold across the whole surface; the tiles link to the guide "
        "that owns each of them.</p>"
        f'<div class="conv-strip">{"".join(tiles)}</div>'
        + openapi_p +
        '<h2 id="areas">Areas</h2>'
        f'<div class="doc-grid">{"".join(cards)}</div>')


def api_search_entries(api):
    """Hub + area + one entry per endpoint, in the existing index shape."""
    areas = api.get("areas") or []
    total = sum(len(a.get("routes") or []) for a in areas)
    entries = [{"p": f"{API_HUB}.html", "t": "API Reference", "s": "", "a": "",
                "x": _plain(f"the control plane serves {total} routes across "
                            f"{len(areas)} areas. authentication, access classes, "
                            "scoping, pagination, errors.")}]
    for area in areas:
        fname = area_filename(area)
        page_t = f"{area_title(area)} API"
        entries.append({"p": f"{fname}.html", "t": page_t, "s": "", "a": "",
                        "x": _plain(str(area.get("description") or ""))})
        for route, anchor, label in area_endpoints(area):
            entries.append({"p": f"{fname}.html", "t": page_t, "s": label, "a": anchor,
                            "x": _plain(str(route.get("summary") or ""))})
    return entries


def render(name, title, description, content, crumb, footnav, sidebar):
    return TEMPLATE.format(name=name, title=title, description=description,
                           content=content, crumb=crumb, footnav=footnav,
                           sidebar=sidebar)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--api-doc", default=str(API_DOC_DEFAULT), metavar="PATH",
                    help="api-doc.json to render the API reference from "
                         "(default: docs/api/api-doc.json; relative paths "
                         "resolve against the repo root)")
    args = ap.parse_args()
    api_path = Path(args.api_doc)
    if not api_path.is_absolute():
        api_path = ROOT / api_path
    api = load_api_doc(api_path)

    openapi = OPENAPI_SRC.exists()
    if openapi:
        shutil.copyfile(OPENAPI_SRC, DOCS / "openapi.json")
        print("docs/openapi.json (copied from docs/api/openapi.json)")

    sections_map = {}
    for name, _, _ in PAGES:
        if name == API_HUB and api:
            sections_map[name] = list(API_HUB_SECTIONS)
            continue
        src = source_for(name)
        if not src.exists():
            sys.exit(f"missing {src}")
        sections_map[name] = sections(src.read_text())

    (DOCS / "assets" / "docs.css").write_text(DOCS_CSS)
    print("docs/assets/docs.css")

    for idx, (name, title, description) in enumerate(PAGES):
        if name == API_HUB and api:
            body = api_hub_content(api, openapi)
            gen_by = str(api.get("generated_by") or "").strip()
            note = (f"Generated by <code>{html_mod.escape(gen_by, quote=False)}</code> "
                    "from the API route registrations." if gen_by else None)
            meta = page_meta(name, src_path=api_path, note=note)
        else:
            body = convert(source_for(name).read_text())
            meta = page_meta(name)
        crumb = '<nav class="crumb"><a href="/documentation.html">Documentation</a> <span>/ ' + title + "</span></nav>"
        prev_page = PAGES[idx - 1] if idx > 0 else None
        next_page = PAGES[idx + 1] if idx + 1 < len(PAGES) else None
        left = f'<a href="/{prev_page[0]}.html">&larr; {prev_page[1]}</a>' if prev_page else "<span></span>"
        right = f'<a href="/{next_page[0]}.html">{next_page[1]} &rarr;</a>' if next_page else "<span></span>"
        footnav = meta + f'<nav class="foot-nav">{left}{right}</nav>'
        (DOCS / f"{name}.html").write_text(
            render(name, title, description, body, crumb, footnav,
                   build_sidebar(name, sections_map)))
        print(f"docs/{name}.html")

    area_files = []
    if api:
        areas = api.get("areas") or []
        area_files = [area_filename(a) for a in areas]
        if len(set(area_files)) != len(area_files):
            sys.exit("error: duplicate area keys in the api doc")
        for i, area in enumerate(areas):
            fname = area_files[i]
            title = area_title(area)
            page_title = html_mod.escape(f"{title} API", quote=True)
            desc = str(area.get("description") or "").strip() \
                or f"API reference for the {title} area."
            crumb = ('<nav class="crumb"><a href="/documentation.html">Documentation</a> '
                     f'<span>/</span> <a href="/{API_HUB}.html">API Reference</a> '
                     f'<span>/ {html_mod.escape(title, quote=False)}</span></nav>')
            left = (f'<a href="/{area_files[i - 1]}.html">&larr; {html_mod.escape(area_title(areas[i - 1]), quote=False)}</a>'
                    if i > 0 else f'<a href="/{API_HUB}.html">&larr; API Reference</a>')
            right = (f'<a href="/{area_files[i + 1]}.html">{html_mod.escape(area_title(areas[i + 1]), quote=False)} &rarr;</a>'
                     if i + 1 < len(areas) else "<span></span>")
            footnav = (page_meta(fname, src_path=api_path, note=GENERATED_API_NOTE)
                       + f'<nav class="foot-nav">{left}{right}</nav>')
            (DOCS / f"{fname}.html").write_text(
                render(fname, page_title, html_mod.escape(desc, quote=True),
                       api_area_content(area), crumb, footnav,
                       build_api_sidebar(api, fname)))
            print(f"docs/{fname}.html")
        keep = {f"{f}.html" for f in area_files}
        for stale in sorted(DOCS.glob("api-*.html")):
            if stale.name != f"{API_HUB}.html" and stale.name not in keep:
                stale.unlink()
                print(f"docs/{stale.name} removed (stale area page)")

    cards = "\n".join(
        f'<a class="doc-card" href="/{name}.html"><h2>{title}</h2><p>{description}</p></a>'
        for name, title, description in PAGES)
    index_content = ("<h1>Documentation</h1>"
                     "<p>Everything you need to run Ryuki — the governed control plane "
                     "for multi-site infrastructure.</p>"
                     f'<div class="doc-grid">{cards}</div>')
    (DOCS / "documentation.html").write_text(
        render("documentation", "Documentation",
               "Guides for running Ryuki: getting started, architecture, "
               "configuration, Entra ID app registration, and site management.",
               index_content, "", "", build_sidebar("documentation", sections_map)))
    print("docs/documentation.html")

    nf_content = (
        "<h1>404 \u2014 page not found</h1>"
        "<p>The ry\u016b guards many treasures, but this page is not among them.</p>"
        '<p><a href="/">Back to ryuki.io</a> \u00b7 '
        '<a href="/documentation.html">Browse the documentation</a></p>')
    nf_html = render("404", "Page not found", "This page does not exist.",
                     nf_content, "", "", build_sidebar("404", sections_map))
    nf_html = nf_html.replace(
        '<link rel="canonical" href="https://ryuki.io/404.html">',
        '<meta name="robots" content="noindex">')
    nf_html = nf_html.replace('<meta property="og:type" content="article">\n', '')
    nf_html = nf_html.replace('<meta property="og:url" content="https://ryuki.io/404.html">\n', '')
    assert 'noindex' in nf_html and 'canonical' not in nf_html
    (DOCS / "404.html").write_text(nf_html)
    print("docs/404.html")

    urls = ["https://ryuki.io/", "https://ryuki.io/documentation.html"] + [
        f"https://ryuki.io/{name}.html" for name, _, _ in PAGES] + [
        f"https://ryuki.io/{fname}.html" for fname in area_files]
    sitemap = ('<?xml version="1.0" encoding="UTF-8"?>\n'
               '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
               + "".join(f"  <url><loc>{u}</loc></url>\n" for u in urls)
               + "</urlset>\n")
    (DOCS / "sitemap.xml").write_text(sitemap)
    print("docs/sitemap.xml")
    (DOCS / "robots.txt").write_text(
        "User-agent: *\nAllow: /\n\nSitemap: https://ryuki.io/sitemap.xml\n")
    print("docs/robots.txt")

    index_entries = []
    for name, title, _ in PAGES:
        if name == API_HUB and api:
            index_entries.extend(api_search_entries(api))
            continue
        index_entries.extend(search_entries(name, title, source_for(name).read_text()))
    (DOCS / "search-index.json").write_text(
        json.dumps(index_entries, separators=(",", ":"), ensure_ascii=False))
    print(f"docs/search-index.json ({len(index_entries)} sections)")


if __name__ == "__main__":
    main()
