//! Opaque verification for independently measured deployed-workload identity.
//!
//! The build manifest declares the OCI subject that release admission expects;
//! it cannot prove that the calling process is actually running from that
//! subject. This module closes only that gap. It creates a nonce-bound request
//! and accepts one short-lived, Ed25519-authenticated peer measurement from an
//! independently pinned authority. Transport and peer measurement remain API
//! responsibilities; this module is pure and performs no I/O.

use std::fmt;

use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64_STANDARD};
use chrono::{DateTime, TimeDelta, Utc};
use ed25519_dalek::{Signature, VerifyingKey};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};
use thiserror::Error;

use crate::conformance_trust::{
    ConformanceTrustedTimeWindow, canonical_json_bytes, parse_json_strict,
};
use crate::production_build::{OciSubject, OciSubjectKind, RuntimeExecutable};
use crate::production_deployment_applicability::DeployedArtifactApplicabilityClaim;

pub const DEPLOYED_WORKLOAD_PROTOCOL_VERSION: &str = "1.0.0";
pub const DEPLOYED_WORKLOAD_REQUEST_DOMAIN: &str = "ryuki-v1/deployed-workload-attestation-request";
pub const DEPLOYED_WORKLOAD_RESPONSE_DOMAIN: &str =
    "ryuki-v1/deployed-workload-attestation-response";

const REQUEST_KIND: &str = "deployed-workload-attestation-request";
const RESPONSE_KIND: &str = "deployed-workload-attestation-response";
const REQUEST_OPERATION: &str = "attest_exact_peer";
const CANONICALIZATION: &str = "ryuki-canonical-json-v1";
const SIGNATURE_ALGORITHM: &str = "ed25519";
const MEASUREMENT_METHOD: &str = "authenticated-peer-runtime-v1";
pub const MAX_DEPLOYED_WORKLOAD_REQUEST_BYTES: usize = 16 * 1024;
pub const MAX_DEPLOYED_WORKLOAD_RESPONSE_BYTES: usize = 64 * 1024;
const MAX_JSON_DEPTH: usize = 16;
const MAX_JSON_NODES: usize = 1024;
const MAX_JSON_COLLECTION_ITEMS: usize = 128;
const MAX_JSON_STRING_BYTES: usize = 4096;
const MAX_ATTESTATION_LIFETIME_SECONDS: i64 = 300;
const MAX_EXACT_JSON_INTEGER: u64 = 9_007_199_254_740_991;
const MAX_RUNTIME_EXECUTABLE_BYTES: u64 = 2 * 1024 * 1024 * 1024;

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum DeployedWorkloadError {
    #[error("invalid deployed-workload attestation: {0}")]
    Invalid(String),
    #[error("deployed-workload authority signature verification failed")]
    SignatureVerificationFailed,
}

/// Independent deployment-time pins for the peer-measurement authority.
#[derive(Debug, Clone, Copy)]
pub struct DeployedWorkloadAuthorityAnchor<'a> {
    pub authority_id: &'a str,
    pub key_id: &'a str,
    pub public_key: &'a [u8; 32],
    pub public_key_fingerprint: &'a str,
    pub minimum_authority_epoch: u64,
    pub measurement_profile_id: &'a str,
    pub measurement_profile_version: u64,
    pub measurement_profile_digest: &'a str,
}

/// Exact workload and build facts that the external measurement must match.
#[derive(Debug, Clone, Copy)]
pub struct ExpectedDeployedWorkload<'a> {
    pub deployment_id: &'a str,
    pub trust_domain_id: &'a str,
    pub workload_id: &'a str,
    pub oci_subject: &'a OciSubject,
    pub runtime_executable: &'a RuntimeExecutable,
}

/// Opaque canonical request for the semantic-free one-shot transport.
///
/// The type is intentionally non-cloneable so one request/nonce is consumed by
/// exactly one verification attempt.
pub struct DeployedWorkloadAttestationRequest {
    canonical_bytes: Box<[u8]>,
    digest: String,
    nonce: String,
    requested_at: DateTime<Utc>,
    authority_id: String,
    authority_key_id: String,
    namespace: AttestationNamespace,
    measurement_profile: MeasurementProfileBinding,
    expected_oci_subject: OciSubject,
    expected_runtime_executable: RuntimeExecutable,
}

impl fmt::Debug for DeployedWorkloadAttestationRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("DeployedWorkloadAttestationRequest")
            .field("digest", &self.digest)
            .field("requested_at", &self.requested_at)
            .field("authority_id", &self.authority_id)
            .field("namespace", &self.namespace)
            .field("byte_len", &self.canonical_bytes.len())
            .finish()
    }
}

impl DeployedWorkloadAttestationRequest {
    pub fn as_bytes(&self) -> &[u8] {
        &self.canonical_bytes
    }

    pub fn digest(&self) -> &str {
        &self.digest
    }
}

/// Creates a bounded canonical request for one exact peer measurement.
///
/// `request_nonce` must be freshly generated by the caller with the operating
/// system CSPRNG and must never be reused for a retry or second authority.
pub fn build_deployed_workload_attestation_request(
    expected: ExpectedDeployedWorkload<'_>,
    authority: DeployedWorkloadAuthorityAnchor<'_>,
    request_nonce: [u8; 32],
    requested_at: DateTime<Utc>,
) -> Result<DeployedWorkloadAttestationRequest, DeployedWorkloadError> {
    validate_authority(authority)?;
    validate_expected(expected)?;
    if request_nonce.iter().all(|byte| *byte == 0) {
        return Err(invalid("request nonce cannot be all zero"));
    }

    let nonce = BASE64_STANDARD.encode(request_nonce);
    let namespace = AttestationNamespace {
        deployment_id: expected.deployment_id.to_owned(),
        trust_domain_id: expected.trust_domain_id.to_owned(),
        workload_id: expected.workload_id.to_owned(),
    };
    let measurement_profile = MeasurementProfileBinding {
        profile_id: authority.measurement_profile_id.to_owned(),
        profile_version: authority.measurement_profile_version,
        content_digest: authority.measurement_profile_digest.to_owned(),
    };
    let value = serde_json::json!({
        "schema_version": DEPLOYED_WORKLOAD_PROTOCOL_VERSION,
        "contract_kind": REQUEST_KIND,
        "operation": REQUEST_OPERATION,
        "canonicalization": CANONICALIZATION,
        "signature_algorithm": SIGNATURE_ALGORITHM,
        "authority_id": authority.authority_id,
        "authority_key_id": authority.key_id,
        "namespace": namespace,
        "measurement_profile": measurement_profile,
        "expected": {
            "oci_subject": expected.oci_subject,
            "runtime_executable": expected.runtime_executable,
        },
        "request_nonce": nonce,
        "requested_at": requested_at,
    });
    let canonical_bytes = canonical_json_bytes(&value)
        .map_err(|error| invalid(format!("request canonicalization failed: {error}")))?;
    if canonical_bytes.is_empty() || canonical_bytes.len() > MAX_DEPLOYED_WORKLOAD_REQUEST_BYTES {
        return Err(invalid("request is empty or exceeds 16 KiB"));
    }
    let digest = sha256_digest(&canonical_bytes);

    Ok(DeployedWorkloadAttestationRequest {
        canonical_bytes: canonical_bytes.into_boxed_slice(),
        digest,
        nonce,
        requested_at,
        authority_id: authority.authority_id.to_owned(),
        authority_key_id: authority.key_id.to_owned(),
        namespace,
        measurement_profile,
        expected_oci_subject: expected.oci_subject.clone(),
        expected_runtime_executable: expected.runtime_executable.clone(),
    })
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct AttestationNamespace {
    deployment_id: String,
    trust_domain_id: String,
    workload_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct MeasurementProfileBinding {
    profile_id: String,
    profile_version: u64,
    content_digest: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct AttestationResponse {
    schema_version: String,
    contract_kind: String,
    canonicalization: String,
    signature_algorithm: String,
    authority: ResponseAuthority,
    request_nonce: String,
    request_digest: String,
    namespace: AttestationNamespace,
    measurement_profile: MeasurementProfileBinding,
    outcome: String,
    measurement: PeerMeasurement,
    #[serde(rename = "signature_base64")]
    _signature_base64: String,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ResponseAuthority {
    authority_id: String,
    key_id: String,
    public_key_fingerprint: String,
    authority_epoch: u64,
    authority_revision: u64,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct PeerMeasurement {
    sequence: u64,
    method: String,
    observed_at: TrustedTimeInterval,
    valid_until: DateTime<Utc>,
    workload_instance_binding_digest: String,
    runtime_state: String,
    restored_state_reconciled: bool,
    deployed_oci_subject: OciSubject,
    subject_resolution: String,
    resolved_image_manifest_digest: String,
    peer_executable: RuntimeExecutable,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct TrustedTimeInterval {
    not_before: DateTime<Utc>,
    not_after: DateTime<Utc>,
}

/// Opaque, non-cloneable proof of exact live peer-to-workload/OCI binding.
///
/// ```compile_fail
/// fn requires_clone<T: Clone>() {}
/// requires_clone::<ryuki_core::deployed_workload::VerifiedDeployedWorkload>();
/// ```
pub struct VerifiedDeployedWorkload {
    raw_response: Box<[u8]>,
    response_digest: String,
    namespace: AttestationNamespace,
    authority_id: String,
    authority_key_id: String,
    authority_public_key_fingerprint: String,
    authority_epoch: u64,
    authority_revision: u64,
    measurement_profile: MeasurementProfileBinding,
    measurement_sequence: u64,
    observed_at: TrustedTimeInterval,
    valid_until: DateTime<Utc>,
    workload_instance_binding_digest: String,
    deployed_oci_subject: OciSubject,
    resolved_image_manifest_digest: String,
    peer_executable: RuntimeExecutable,
}

impl fmt::Debug for VerifiedDeployedWorkload {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("VerifiedDeployedWorkload")
            .field("response_digest", &self.response_digest)
            .field("deployment_id", &self.namespace.deployment_id)
            .field("trust_domain_id", &self.namespace.trust_domain_id)
            .field("workload_id", &self.namespace.workload_id)
            .field("authority_id", &self.authority_id)
            .field("authority_key_id", &self.authority_key_id)
            .field(
                "authority_public_key_fingerprint",
                &self.authority_public_key_fingerprint,
            )
            .field("authority_epoch", &self.authority_epoch)
            .field("authority_revision", &self.authority_revision)
            .field("measurement_profile", &self.measurement_profile)
            .field("measurement_sequence", &self.measurement_sequence)
            .field("oci_repository", &self.deployed_oci_subject.repository)
            .field(
                "oci_subject_digest",
                &self.deployed_oci_subject.content_digest,
            )
            .field("valid_until", &self.valid_until)
            .field("byte_len", &self.raw_response.len())
            .finish()
    }
}

impl VerifiedDeployedWorkload {
    pub fn ensure_fresh(
        &self,
        trusted_now: ConformanceTrustedTimeWindow,
    ) -> Result<(), DeployedWorkloadError> {
        if trusted_now.not_before > trusted_now.not_after
            || self.observed_at.not_after > trusted_now.not_before
            || trusted_now.not_after >= self.valid_until
        {
            return Err(invalid(
                "verified deployed-workload measurement is stale at the startup fence",
            ));
        }
        Ok(())
    }

    pub fn deployment_id(&self) -> &str {
        &self.namespace.deployment_id
    }

    pub fn trust_domain_id(&self) -> &str {
        &self.namespace.trust_domain_id
    }

    pub fn workload_id(&self) -> &str {
        &self.namespace.workload_id
    }

    pub fn authority_id(&self) -> &str {
        &self.authority_id
    }

    pub fn authority_key_id(&self) -> &str {
        &self.authority_key_id
    }

    pub fn authority_public_key_fingerprint(&self) -> &str {
        &self.authority_public_key_fingerprint
    }

    pub fn authority_epoch(&self) -> u64 {
        self.authority_epoch
    }

    pub fn authority_revision(&self) -> u64 {
        self.authority_revision
    }

    pub fn measurement_profile_id(&self) -> &str {
        &self.measurement_profile.profile_id
    }

    pub fn measurement_profile_version(&self) -> u64 {
        self.measurement_profile.profile_version
    }

    pub fn measurement_profile_digest(&self) -> &str {
        &self.measurement_profile.content_digest
    }

    pub fn measurement_sequence(&self) -> u64 {
        self.measurement_sequence
    }

    pub fn oci_subject_kind(&self) -> OciSubjectKind {
        self.deployed_oci_subject.subject_kind
    }

    pub fn oci_repository(&self) -> &str {
        &self.deployed_oci_subject.repository
    }

    pub fn oci_subject_digest(&self) -> &str {
        &self.deployed_oci_subject.content_digest
    }

    pub fn resolved_manifest_digest(&self) -> &str {
        &self.resolved_image_manifest_digest
    }

    pub fn runtime_executable_digest(&self) -> &str {
        &self.peer_executable.content_digest
    }

    pub fn runtime_executable_byte_length(&self) -> u64 {
        self.peer_executable.byte_length
    }

    pub fn workload_instance_binding_digest(&self) -> &str {
        &self.workload_instance_binding_digest
    }

    pub fn observed_at_not_before(&self) -> DateTime<Utc> {
        self.observed_at.not_before
    }

    pub fn observed_at_not_after(&self) -> DateTime<Utc> {
        self.observed_at.not_after
    }

    pub fn response_digest(&self) -> &str {
        &self.response_digest
    }

    pub fn valid_until(&self) -> DateTime<Utc> {
        self.valid_until
    }

    /// Data-only compatibility projection. This value is intentionally not an
    /// authority capability and cannot recreate this proof.
    pub fn applicability_claim(&self) -> DeployedArtifactApplicabilityClaim {
        DeployedArtifactApplicabilityClaim {
            subject_kind: self.deployed_oci_subject.subject_kind,
            repository: self.deployed_oci_subject.repository.clone(),
            subject_digest: self.deployed_oci_subject.content_digest.clone(),
        }
    }
}

/// Verifies and consumes one request against one exact signed response.
pub fn verify_deployed_workload_attestation(
    request: DeployedWorkloadAttestationRequest,
    raw_response: &[u8],
    authority: DeployedWorkloadAuthorityAnchor<'_>,
    trusted_now: ConformanceTrustedTimeWindow,
) -> Result<VerifiedDeployedWorkload, DeployedWorkloadError> {
    validate_authority(authority)?;
    if request.authority_id != authority.authority_id
        || request.authority_key_id != authority.key_id
        || request.measurement_profile.profile_id != authority.measurement_profile_id
        || request.measurement_profile.profile_version != authority.measurement_profile_version
        || request.measurement_profile.content_digest != authority.measurement_profile_digest
        || sha256_digest(request.as_bytes()) != request.digest
    {
        return Err(invalid(
            "request was not produced for this authority and measurement profile",
        ));
    }
    if trusted_now.not_before > trusted_now.not_after {
        return Err(invalid("trusted local time interval is inverted"));
    }
    if raw_response.is_empty() || raw_response.len() > MAX_DEPLOYED_WORKLOAD_RESPONSE_BYTES {
        return Err(invalid("response is empty or exceeds 64 KiB"));
    }

    let value = parse_json_strict(raw_response)
        .map_err(|error| invalid(format!("strict response JSON failed: {error}")))?;
    let mut nodes = 0;
    validate_json_shape(&value, 0, &mut nodes)?;
    validate_timestamp_lexemes(&value)?;
    verify_response_signature(&value, authority)?;
    let response: AttestationResponse = serde_json::from_value(value)
        .map_err(|error| invalid(format!("response typed decoding failed: {error}")))?;

    if response.schema_version != DEPLOYED_WORKLOAD_PROTOCOL_VERSION
        || response.contract_kind != RESPONSE_KIND
        || response.canonicalization != CANONICALIZATION
        || response.signature_algorithm != SIGNATURE_ALGORITHM
        || response.authority.authority_id != authority.authority_id
        || response.authority.key_id != authority.key_id
        || response.authority.public_key_fingerprint != authority.public_key_fingerprint
        || response.request_nonce != request.nonce
        || response.request_digest != request.digest
        || response.namespace != request.namespace
        || response.measurement_profile != request.measurement_profile
        || response.outcome != "matched"
        || response.measurement.method != MEASUREMENT_METHOD
        || response.measurement.runtime_state != "running"
        || !response.measurement.restored_state_reconciled
    {
        return Err(invalid(
            "response profile, authority, request echo, namespace, or matched state differs",
        ));
    }

    if !valid_counter(response.authority.authority_epoch)
        || response.authority.authority_epoch < authority.minimum_authority_epoch
        || !valid_counter(response.authority.authority_revision)
        || !valid_counter(response.measurement.sequence)
    {
        return Err(invalid(
            "response authority epoch, revision, or measurement sequence is invalid",
        ));
    }
    if response.measurement.deployed_oci_subject != request.expected_oci_subject
        || response.measurement.peer_executable != request.expected_runtime_executable
    {
        return Err(invalid(
            "measured OCI subject or peer executable differs from the exact request",
        ));
    }
    validate_subject_resolution(&response.measurement)?;
    require_digest(
        "workload instance binding",
        &response.measurement.workload_instance_binding_digest,
    )?;

    let observed = &response.measurement.observed_at;
    let valid_until = response.measurement.valid_until;
    if request.requested_at > observed.not_before
        || observed.not_before > observed.not_after
        || observed.not_after > trusted_now.not_before
        || trusted_now.not_after >= valid_until
        || valid_until <= observed.not_after
        || valid_until.signed_duration_since(observed.not_before)
            > TimeDelta::seconds(MAX_ATTESTATION_LIFETIME_SECONDS)
    {
        return Err(invalid(
            "response observation interval or exclusive freshness bound is invalid",
        ));
    }

    Ok(VerifiedDeployedWorkload {
        raw_response: raw_response.to_vec().into_boxed_slice(),
        response_digest: sha256_digest(raw_response),
        namespace: response.namespace,
        authority_id: response.authority.authority_id,
        authority_key_id: response.authority.key_id,
        authority_public_key_fingerprint: response.authority.public_key_fingerprint,
        authority_epoch: response.authority.authority_epoch,
        authority_revision: response.authority.authority_revision,
        measurement_profile: response.measurement_profile,
        measurement_sequence: response.measurement.sequence,
        observed_at: response.measurement.observed_at,
        valid_until,
        workload_instance_binding_digest: response.measurement.workload_instance_binding_digest,
        deployed_oci_subject: response.measurement.deployed_oci_subject,
        resolved_image_manifest_digest: response.measurement.resolved_image_manifest_digest,
        peer_executable: response.measurement.peer_executable,
    })
}

fn validate_authority(
    authority: DeployedWorkloadAuthorityAnchor<'_>,
) -> Result<(), DeployedWorkloadError> {
    if !valid_scoped_id(
        authority.authority_id,
        "deployed-workload-attestation-authority:",
    ) || !valid_scoped_id(authority.key_id, "deployed-workload-attestation-key:")
        || !valid_scoped_id(
            authority.measurement_profile_id,
            "deployed-workload-measurement-profile:",
        )
        || !valid_counter(authority.minimum_authority_epoch)
        || !valid_counter(authority.measurement_profile_version)
        || !is_digest(authority.public_key_fingerprint)
        || !is_digest(authority.measurement_profile_digest)
    {
        return Err(invalid("invalid independent workload authority anchor"));
    }
    if sha256_digest(authority.public_key) != authority.public_key_fingerprint {
        return Err(invalid(
            "workload authority public key does not match its fingerprint pin",
        ));
    }
    let verifying_key = VerifyingKey::from_bytes(authority.public_key)
        .map_err(|_| invalid("invalid workload authority Ed25519 key"))?;
    if verifying_key.is_weak() {
        return Err(invalid("weak workload authority Ed25519 key"));
    }
    Ok(())
}

fn validate_expected(expected: ExpectedDeployedWorkload<'_>) -> Result<(), DeployedWorkloadError> {
    if !valid_scoped_id(expected.deployment_id, "deployment:")
        || !valid_scoped_id(expected.trust_domain_id, "trust-domain:")
        || !valid_scoped_id(expected.workload_id, "workload:")
        || !is_oci_repository(&expected.oci_subject.repository)
    {
        return Err(invalid(
            "invalid expected workload namespace or OCI repository",
        ));
    }
    require_digest("expected OCI subject", &expected.oci_subject.content_digest)?;
    require_digest(
        "expected runtime executable",
        &expected.runtime_executable.content_digest,
    )?;
    if expected.runtime_executable.byte_length == 0
        || expected.runtime_executable.byte_length > MAX_RUNTIME_EXECUTABLE_BYTES
    {
        return Err(invalid(
            "expected runtime executable byte length is outside the production bound",
        ));
    }
    Ok(())
}

fn validate_subject_resolution(measurement: &PeerMeasurement) -> Result<(), DeployedWorkloadError> {
    require_digest(
        "resolved image manifest",
        &measurement.resolved_image_manifest_digest,
    )?;
    match measurement.deployed_oci_subject.subject_kind {
        OciSubjectKind::OciImageManifest
            if measurement.subject_resolution == "direct_manifest"
                && measurement.resolved_image_manifest_digest
                    == measurement.deployed_oci_subject.content_digest =>
        {
            Ok(())
        }
        OciSubjectKind::OciImageIndex
            if measurement.subject_resolution == "index_member"
                && measurement.resolved_image_manifest_digest
                    != measurement.deployed_oci_subject.content_digest =>
        {
            Ok(())
        }
        _ => Err(invalid(
            "OCI subject resolution is inconsistent with the exact subject kind",
        )),
    }
}

fn verify_response_signature(
    value: &Value,
    authority: DeployedWorkloadAuthorityAnchor<'_>,
) -> Result<(), DeployedWorkloadError> {
    let signature_base64 = value
        .get("signature_base64")
        .and_then(Value::as_str)
        .ok_or_else(|| invalid("response omits signature_base64"))?;
    let signature_bytes = decode_canonical_base64::<64>(signature_base64, "response signature")?;
    let signature = Signature::from_bytes(&signature_bytes);

    let mut subject = value.clone();
    subject
        .as_object_mut()
        .ok_or_else(|| invalid("response root is not an object"))?
        .remove("signature_base64");
    let canonical_subject = canonical_json_bytes(&subject)
        .map_err(|error| invalid(format!("response canonicalization failed: {error}")))?;
    let mut signed =
        Vec::with_capacity(16 + DEPLOYED_WORKLOAD_RESPONSE_DOMAIN.len() + canonical_subject.len());
    write_frame(&mut signed, DEPLOYED_WORKLOAD_RESPONSE_DOMAIN.as_bytes());
    write_frame(&mut signed, &canonical_subject);

    let key = VerifyingKey::from_bytes(authority.public_key)
        .map_err(|_| invalid("invalid workload authority Ed25519 key"))?;
    key.verify_strict(&signed, &signature)
        .map_err(|_| DeployedWorkloadError::SignatureVerificationFailed)
}

fn validate_timestamp_lexemes(value: &Value) -> Result<(), DeployedWorkloadError> {
    for pointer in [
        "/measurement/observed_at/not_before",
        "/measurement/observed_at/not_after",
        "/measurement/valid_until",
    ] {
        let timestamp = value
            .pointer(pointer)
            .and_then(Value::as_str)
            .ok_or_else(|| invalid(format!("response timestamp {pointer} is missing")))?;
        if timestamp.is_empty()
            || timestamp.len() > 35
            || timestamp.trim() != timestamp
            || DateTime::parse_from_rfc3339(timestamp).is_err()
        {
            return Err(invalid(format!(
                "response timestamp {pointer} is not canonical bounded RFC3339"
            )));
        }
    }
    Ok(())
}

fn validate_json_shape(
    value: &Value,
    depth: usize,
    nodes: &mut usize,
) -> Result<(), DeployedWorkloadError> {
    if depth > MAX_JSON_DEPTH {
        return Err(invalid("response JSON exceeds the nesting-depth bound"));
    }
    *nodes = nodes
        .checked_add(1)
        .ok_or_else(|| invalid("response JSON node counter overflowed"))?;
    if *nodes > MAX_JSON_NODES {
        return Err(invalid("response JSON exceeds the node-count bound"));
    }
    match value {
        Value::String(value) if value.len() > MAX_JSON_STRING_BYTES => {
            Err(invalid("response JSON contains an oversized string"))
        }
        Value::Array(values) => {
            if values.len() > MAX_JSON_COLLECTION_ITEMS {
                return Err(invalid("response JSON contains an oversized array"));
            }
            for value in values {
                validate_json_shape(value, depth + 1, nodes)?;
            }
            Ok(())
        }
        Value::Object(values) => {
            if values.len() > MAX_JSON_COLLECTION_ITEMS {
                return Err(invalid("response JSON contains an oversized object"));
            }
            for (key, value) in values {
                if key.len() > MAX_JSON_STRING_BYTES {
                    return Err(invalid("response JSON contains an oversized key"));
                }
                validate_json_shape(value, depth + 1, nodes)?;
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

fn decode_canonical_base64<const N: usize>(
    value: &str,
    label: &str,
) -> Result<[u8; N], DeployedWorkloadError> {
    let decoded = BASE64_STANDARD
        .decode(value)
        .map_err(|_| invalid(format!("{label} is not valid base64")))?;
    let decoded: [u8; N] = decoded
        .try_into()
        .map_err(|_| invalid(format!("{label} has the wrong decoded length")))?;
    if BASE64_STANDARD.encode(decoded) != value {
        return Err(invalid(format!("{label} is not canonical base64")));
    }
    Ok(decoded)
}

fn write_frame(buffer: &mut Vec<u8>, value: &[u8]) {
    buffer.extend_from_slice(&(value.len() as u64).to_le_bytes());
    buffer.extend_from_slice(value);
}

fn sha256_digest(bytes: &[u8]) -> String {
    format!("sha256:{:x}", Sha256::digest(bytes))
}

fn require_digest(label: &str, value: &str) -> Result<(), DeployedWorkloadError> {
    if is_digest(value) {
        Ok(())
    } else {
        Err(invalid(format!("{label} digest is invalid")))
    }
}

fn is_digest(value: &str) -> bool {
    value.len() == 71
        && value.starts_with("sha256:")
        && value[7..]
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        && value[7..].bytes().any(|byte| byte != b'0')
}

fn valid_counter(value: u64) -> bool {
    value > 0 && value <= MAX_EXACT_JSON_INTEGER
}

fn valid_scoped_id(value: &str, prefix: &str) -> bool {
    let Some(suffix) = value.strip_prefix(prefix) else {
        return false;
    };
    (3..=127).contains(&suffix.len())
        && suffix
            .as_bytes()
            .first()
            .is_some_and(u8::is_ascii_alphanumeric)
        && suffix.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || b"._-".contains(&byte)
        })
}

fn is_oci_repository(value: &str) -> bool {
    (3..=256).contains(&value.len())
        && !value.contains('@')
        && !value.contains(':')
        && !value.contains("//")
        && value.split('/').all(|part| {
            !part.is_empty()
                && !matches!(part, "." | "..")
                && part
                    .as_bytes()
                    .first()
                    .is_some_and(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit())
                && part.bytes().skip(1).all(|byte| {
                    byte.is_ascii_lowercase()
                        || byte.is_ascii_digit()
                        || matches!(byte, b'.' | b'_' | b'-')
                })
        })
}

fn invalid(message: impl Into<String>) -> DeployedWorkloadError {
    DeployedWorkloadError::Invalid(message.into())
}

#[cfg(any(test, feature = "security-test-support"))]
pub mod tests {
    #![cfg_attr(not(test), allow(dead_code, unused_imports))]

    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    use base64::Engine as _;
    use chrono::TimeZone;
    use ed25519_dalek::{Signer, SigningKey};
    use serde_json::{Map, json};
    use sha2::Digest as _;

    use super::*;

    static TEST_ENTROPY_COUNTER: AtomicU64 = AtomicU64::new(1);

    /// Stable, non-secret workload identity used only by genuine downstream
    /// composition fixtures that must bind an independently signed proof to a
    /// deterministic ingress preimage.
    #[cfg(feature = "security-test-support")]
    pub fn genuine_workload_instance_binding_digest() -> String {
        sha256_digest(b"ryuki genuine production composition workload instance v1")
    }

    struct Fixture {
        signing_key: SigningKey,
        public_key: [u8; 32],
        public_key_fingerprint: String,
        measurement_profile_digest: String,
        oci_subject: OciSubject,
        runtime_executable: RuntimeExecutable,
        resolved_manifest_digest: String,
    }

    impl Fixture {
        fn new(subject_kind: OciSubjectKind) -> Self {
            let signing_key = SigningKey::from_bytes(&test_entropy(b"attestation signing key"));
            let public_key = signing_key.verifying_key().to_bytes();
            let public_key_fingerprint = sha256_digest(&public_key);
            let measurement_profile_digest = digest_for(b"measurement profile");
            let subject_label: &[u8] = match subject_kind {
                OciSubjectKind::OciImageManifest => b"direct OCI manifest",
                OciSubjectKind::OciImageIndex => b"multi-platform OCI index",
            };
            let oci_subject = OciSubject {
                subject_kind,
                repository: "registry.example.test/ryuki/api".to_owned(),
                content_digest: digest_for(subject_label),
            };
            let resolved_manifest_digest = match subject_kind {
                OciSubjectKind::OciImageManifest => oci_subject.content_digest.clone(),
                OciSubjectKind::OciImageIndex => digest_for(b"resolved OCI index member"),
            };
            let runtime_executable = RuntimeExecutable {
                content_digest: digest_for(b"runtime executable"),
                byte_length: 4_096,
            };
            Self {
                signing_key,
                public_key,
                public_key_fingerprint,
                measurement_profile_digest,
                oci_subject,
                runtime_executable,
                resolved_manifest_digest,
            }
        }

        fn authority(&self) -> DeployedWorkloadAuthorityAnchor<'_> {
            DeployedWorkloadAuthorityAnchor {
                authority_id: "deployed-workload-attestation-authority:test",
                key_id: "deployed-workload-attestation-key:test",
                public_key: &self.public_key,
                public_key_fingerprint: &self.public_key_fingerprint,
                minimum_authority_epoch: 7,
                measurement_profile_id: "deployed-workload-measurement-profile:test",
                measurement_profile_version: 3,
                measurement_profile_digest: &self.measurement_profile_digest,
            }
        }

        fn expected(&self) -> ExpectedDeployedWorkload<'_> {
            ExpectedDeployedWorkload {
                deployment_id: "deployment:test",
                trust_domain_id: "trust-domain:test",
                workload_id: "workload:test",
                oci_subject: &self.oci_subject,
                runtime_executable: &self.runtime_executable,
            }
        }

        fn request(&self) -> DeployedWorkloadAttestationRequest {
            build_deployed_workload_attestation_request(
                self.expected(),
                self.authority(),
                test_entropy(b"attestation request nonce"),
                instant(0),
            )
            .expect("fixture request should be valid")
        }

        fn unsigned_response(&self, request: &DeployedWorkloadAttestationRequest) -> Value {
            let (subject_resolution, resolved_image_manifest_digest) =
                match request.expected_oci_subject.subject_kind {
                    OciSubjectKind::OciImageManifest => (
                        "direct_manifest",
                        request.expected_oci_subject.content_digest.clone(),
                    ),
                    OciSubjectKind::OciImageIndex => {
                        ("index_member", self.resolved_manifest_digest.clone())
                    }
                };
            json!({
                "schema_version": DEPLOYED_WORKLOAD_PROTOCOL_VERSION,
                "contract_kind": RESPONSE_KIND,
                "canonicalization": CANONICALIZATION,
                "signature_algorithm": SIGNATURE_ALGORITHM,
                "authority": {
                    "authority_id": self.authority().authority_id,
                    "key_id": self.authority().key_id,
                    "public_key_fingerprint": self.public_key_fingerprint,
                    "authority_epoch": 7,
                    "authority_revision": 11,
                },
                "request_nonce": request.nonce,
                "request_digest": request.digest,
                "namespace": {
                    "deployment_id": request.namespace.deployment_id,
                    "trust_domain_id": request.namespace.trust_domain_id,
                    "workload_id": request.namespace.workload_id,
                },
                "measurement_profile": {
                    "profile_id": request.measurement_profile.profile_id,
                    "profile_version": request.measurement_profile.profile_version,
                    "content_digest": request.measurement_profile.content_digest,
                },
                "outcome": "matched",
                "measurement": {
                    "sequence": 19,
                    "method": MEASUREMENT_METHOD,
                    "observed_at": {
                        "not_before": instant(1),
                        "not_after": instant(2),
                    },
                    "valid_until": instant(240),
                    "workload_instance_binding_digest": digest_for(b"workload instance binding"),
                    "runtime_state": "running",
                    "restored_state_reconciled": true,
                    "deployed_oci_subject": request.expected_oci_subject,
                    "subject_resolution": subject_resolution,
                    "resolved_image_manifest_digest": resolved_image_manifest_digest,
                    "peer_executable": request.expected_runtime_executable,
                },
            })
        }

        fn response_with(
            &self,
            request: &DeployedWorkloadAttestationRequest,
            mutate: impl FnOnce(&mut Value),
        ) -> Vec<u8> {
            let mut response = self.unsigned_response(request);
            mutate(&mut response);
            sign_response(
                response,
                &self.signing_key,
                DEPLOYED_WORKLOAD_RESPONSE_DOMAIN,
            )
        }

        fn response_with_domain(
            &self,
            request: &DeployedWorkloadAttestationRequest,
            domain: &str,
        ) -> Vec<u8> {
            sign_response(self.unsigned_response(request), &self.signing_key, domain)
        }

        fn verify(
            &self,
            request: DeployedWorkloadAttestationRequest,
            response: &[u8],
        ) -> Result<VerifiedDeployedWorkload, DeployedWorkloadError> {
            verify_deployed_workload_attestation(
                request,
                response,
                self.authority(),
                trusted_time(),
            )
        }
    }

    fn instant(offset_seconds: i64) -> DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 7, 17, 8, 0, 0)
            .single()
            .expect("fixture instant is valid")
            + TimeDelta::seconds(offset_seconds)
    }

    fn trusted_time() -> ConformanceTrustedTimeWindow {
        ConformanceTrustedTimeWindow {
            not_before: instant(3),
            not_after: instant(4),
        }
    }

    fn digest_for(label: &[u8]) -> String {
        let mut material = Vec::with_capacity(label.len() + 32);
        material.extend_from_slice(label);
        material.extend_from_slice(&test_entropy(b"digest fixture"));
        sha256_digest(&material)
    }

    fn test_entropy(label: &[u8]) -> [u8; 32] {
        let counter = TEST_ENTROPY_COUNTER.fetch_add(1, Ordering::Relaxed);
        let elapsed = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let mut hasher = Sha256::new();
        hasher.update(b"ryuki deployed-workload test entropy");
        hasher.update(label);
        hasher.update(std::process::id().to_le_bytes());
        hasher.update(counter.to_le_bytes());
        hasher.update(elapsed.to_le_bytes());
        hasher.finalize().into()
    }

    fn sign_response(mut response: Value, key: &SigningKey, domain: &str) -> Vec<u8> {
        response
            .as_object_mut()
            .expect("fixture response is an object")
            .remove("signature_base64");
        let canonical = canonical_json_bytes(&response).expect("fixture response canonicalizes");
        let mut signing_bytes = Vec::new();
        write_frame(&mut signing_bytes, domain.as_bytes());
        write_frame(&mut signing_bytes, &canonical);
        let signature = key.sign(&signing_bytes);
        response
            .as_object_mut()
            .expect("fixture response is an object")
            .insert(
                "signature_base64".to_owned(),
                Value::String(BASE64_STANDARD.encode(signature.to_bytes())),
            );
        serde_json::to_vec(&response).expect("fixture response serializes")
    }

    fn assert_invalid<T>(result: Result<T, DeployedWorkloadError>) {
        assert!(matches!(result, Err(DeployedWorkloadError::Invalid(_))));
    }

    fn verify_mutation(
        subject_kind: OciSubjectKind,
        mutate: impl FnOnce(&mut Value),
    ) -> Result<VerifiedDeployedWorkload, DeployedWorkloadError> {
        let fixture = Fixture::new(subject_kind);
        let request = fixture.request();
        let response = fixture.response_with(&request, mutate);
        fixture.verify(request, &response)
    }

    /// Produces a genuinely signed workload proof for downstream composition
    /// tests while preserving the production verifier as the only constructor
    /// of `VerifiedDeployedWorkload`.
    #[cfg(feature = "security-test-support")]
    pub fn genuine_deployed_workload_fixture(
        deployment_id: &str,
        trust_domain_id: &str,
        workload_id: &str,
        oci_subject: &OciSubject,
        runtime_executable: &RuntimeExecutable,
        valid_for_seconds: i64,
    ) -> Result<VerifiedDeployedWorkload, DeployedWorkloadError> {
        genuine_deployed_workload_fixture_with_optional_instance_binding(
            deployment_id,
            trust_domain_id,
            workload_id,
            oci_subject,
            runtime_executable,
            None,
            valid_for_seconds,
        )
    }

    /// Produces the same genuinely signed workload proof as
    /// [`genuine_deployed_workload_fixture`], but with an explicit stable
    /// workload-instance binding for deterministic cross-module composition
    /// tests. The original helper deliberately retains its independently
    /// randomized binding semantics.
    #[cfg(feature = "security-test-support")]
    pub fn genuine_deployed_workload_fixture_with_instance_binding(
        deployment_id: &str,
        trust_domain_id: &str,
        workload_id: &str,
        oci_subject: &OciSubject,
        runtime_executable: &RuntimeExecutable,
        workload_instance_binding_digest: &str,
        valid_for_seconds: i64,
    ) -> Result<VerifiedDeployedWorkload, DeployedWorkloadError> {
        genuine_deployed_workload_fixture_with_optional_instance_binding(
            deployment_id,
            trust_domain_id,
            workload_id,
            oci_subject,
            runtime_executable,
            Some(workload_instance_binding_digest),
            valid_for_seconds,
        )
    }

    #[cfg(feature = "security-test-support")]
    fn genuine_deployed_workload_fixture_with_optional_instance_binding(
        deployment_id: &str,
        trust_domain_id: &str,
        workload_id: &str,
        oci_subject: &OciSubject,
        runtime_executable: &RuntimeExecutable,
        workload_instance_binding_digest: Option<&str>,
        valid_for_seconds: i64,
    ) -> Result<VerifiedDeployedWorkload, DeployedWorkloadError> {
        let composition_base = Utc
            .with_ymd_and_hms(2026, 7, 16, 12, 0, 0)
            .single()
            .expect("composition fixture instant is valid");
        let mut fixture = Fixture::new(oci_subject.subject_kind);
        fixture.oci_subject = oci_subject.clone();
        fixture.runtime_executable = runtime_executable.clone();
        fixture.resolved_manifest_digest = match oci_subject.subject_kind {
            OciSubjectKind::OciImageManifest => oci_subject.content_digest.clone(),
            OciSubjectKind::OciImageIndex => digest_for(b"resolved fixture OCI index member"),
        };
        let request = build_deployed_workload_attestation_request(
            ExpectedDeployedWorkload {
                deployment_id,
                trust_domain_id,
                workload_id,
                oci_subject: &fixture.oci_subject,
                runtime_executable: &fixture.runtime_executable,
            },
            fixture.authority(),
            test_entropy(b"downstream composition request nonce"),
            composition_base - TimeDelta::seconds(5),
        )?;
        let response = fixture.response_with(&request, |response| {
            response["measurement"]["observed_at"]["not_before"] =
                json!(composition_base - TimeDelta::seconds(2));
            response["measurement"]["observed_at"]["not_after"] =
                json!(composition_base - TimeDelta::seconds(1));
            response["measurement"]["valid_until"] =
                json!(composition_base + TimeDelta::seconds(valid_for_seconds));
            if let Some(workload_instance_binding_digest) = workload_instance_binding_digest {
                response["measurement"]["workload_instance_binding_digest"] =
                    json!(workload_instance_binding_digest);
            }
        });
        verify_deployed_workload_attestation(
            request,
            &response,
            fixture.authority(),
            ConformanceTrustedTimeWindow {
                not_before: composition_base + TimeDelta::seconds(1),
                not_after: composition_base + TimeDelta::seconds(2),
            },
        )
    }

    #[test]
    fn verifies_direct_manifest_and_projects_non_authoritative_applicability() {
        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let request_digest = request.digest().to_owned();
        let response = fixture.response_with(&request, |_| {});
        let proof = fixture
            .verify(request, &response)
            .expect("direct manifest attestation should verify");

        assert_eq!(proof.deployment_id(), "deployment:test");
        assert_eq!(proof.trust_domain_id(), "trust-domain:test");
        assert_eq!(proof.workload_id(), "workload:test");
        assert_eq!(proof.authority_id(), fixture.authority().authority_id);
        assert_eq!(proof.authority_key_id(), fixture.authority().key_id);
        assert_eq!(
            proof.authority_public_key_fingerprint(),
            fixture.public_key_fingerprint
        );
        assert_eq!(proof.authority_epoch(), 7);
        assert_eq!(proof.authority_revision(), 11);
        assert_eq!(
            proof.measurement_profile_id(),
            fixture.authority().measurement_profile_id
        );
        assert_eq!(proof.measurement_profile_version(), 3);
        assert_eq!(
            proof.measurement_profile_digest(),
            fixture.measurement_profile_digest
        );
        assert_eq!(proof.measurement_sequence(), 19);
        assert_eq!(proof.oci_subject_kind(), OciSubjectKind::OciImageManifest);
        assert_eq!(proof.oci_repository(), fixture.oci_subject.repository);
        assert_eq!(
            proof.oci_subject_digest(),
            fixture.oci_subject.content_digest
        );
        assert_eq!(
            proof.resolved_manifest_digest(),
            fixture.oci_subject.content_digest
        );
        assert_eq!(
            proof.runtime_executable_digest(),
            fixture.runtime_executable.content_digest
        );
        assert_eq!(proof.runtime_executable_byte_length(), 4_096);
        assert_eq!(
            proof.workload_instance_binding_digest(),
            digest_from_response(&response, "/measurement/workload_instance_binding_digest")
        );
        assert_eq!(proof.response_digest(), sha256_digest(&response));
        assert_eq!(proof.valid_until(), instant(240));
        proof
            .ensure_fresh(trusted_time())
            .expect("new proof should remain fresh at the startup fence");

        let claim = proof.applicability_claim();
        assert_eq!(claim.subject_kind, OciSubjectKind::OciImageManifest);
        assert_eq!(claim.repository, fixture.oci_subject.repository);
        assert_eq!(claim.subject_digest, fixture.oci_subject.content_digest);

        let debug = format!("{proof:?}");
        assert!(debug.contains("VerifiedDeployedWorkload"));
        assert!(!debug.contains(&BASE64_STANDARD.encode(fixture.public_key)));
        assert!(!debug.contains(&request_digest));
        assert!(!debug.contains("signature_base64"));
    }

    #[test]
    fn verifies_index_member_resolution() {
        let fixture = Fixture::new(OciSubjectKind::OciImageIndex);
        let request = fixture.request();
        let response = fixture.response_with(&request, |_| {});
        let proof = fixture
            .verify(request, &response)
            .expect("index member attestation should verify");

        assert_eq!(proof.oci_subject_kind(), OciSubjectKind::OciImageIndex);
        assert_eq!(
            proof.oci_subject_digest(),
            fixture.oci_subject.content_digest
        );
        assert_eq!(
            proof.resolved_manifest_digest(),
            fixture.resolved_manifest_digest
        );
        assert_ne!(proof.oci_subject_digest(), proof.resolved_manifest_digest());
    }

    #[test]
    fn rejects_tampered_signature_wrong_key_fingerprint_and_domain() {
        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let mut response: Value = serde_json::from_slice(&fixture.response_with(&request, |_| {}))
            .expect("fixture response parses");
        let mut signature = BASE64_STANDARD
            .decode(
                response["signature_base64"]
                    .as_str()
                    .expect("fixture signature is present"),
            )
            .expect("fixture signature is base64");
        signature[0] ^= 1;
        response["signature_base64"] = Value::String(BASE64_STANDARD.encode(signature));
        let response = serde_json::to_vec(&response).expect("tampered response serializes");
        assert!(matches!(
            fixture.verify(request, &response),
            Err(DeployedWorkloadError::SignatureVerificationFailed)
        ));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let response = fixture.response_with_domain(&request, DEPLOYED_WORKLOAD_REQUEST_DOMAIN);
        assert!(matches!(
            fixture.verify(request, &response),
            Err(DeployedWorkloadError::SignatureVerificationFailed)
        ));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let response = fixture.response_with(&request, |_| {});
        let other_key = SigningKey::from_bytes(&test_entropy(b"substituted authority key"));
        let other_public = other_key.verifying_key().to_bytes();
        let other_fingerprint = sha256_digest(&other_public);
        let mut wrong_key = fixture.authority();
        wrong_key.public_key = &other_public;
        wrong_key.public_key_fingerprint = &other_fingerprint;
        assert!(matches!(
            verify_deployed_workload_attestation(request, &response, wrong_key, trusted_time()),
            Err(DeployedWorkloadError::SignatureVerificationFailed)
        ));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let response = fixture.response_with(&request, |_| {});
        let mismatched_fingerprint = digest_for(b"wrong authority fingerprint");
        let mut bad_pin = fixture.authority();
        bad_pin.public_key_fingerprint = &mismatched_fingerprint;
        assert_invalid(verify_deployed_workload_attestation(
            request,
            &response,
            bad_pin,
            trusted_time(),
        ));
    }

    #[test]
    fn rejects_nonce_digest_namespace_and_profile_substitution() {
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| {
                response["request_nonce"] =
                    json!(BASE64_STANDARD.encode(test_entropy(b"wrong nonce")))
            },
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["request_digest"] = json!(digest_for(b"wrong request digest")),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["namespace"]["workload_id"] = json!("workload:substituted"),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["namespace"]["trust_domain_id"] = json!("trust-domain:substituted"),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement_profile"]["profile_version"] = json!(4),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| {
                response["measurement_profile"]["content_digest"] =
                    json!(digest_for(b"wrong profile"))
            },
        ));
    }

    #[test]
    fn rejects_oci_executable_and_live_state_substitution() {
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| {
                response["measurement"]["deployed_oci_subject"]["content_digest"] =
                    json!(digest_for(b"wrong OCI subject"))
            },
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| {
                response["measurement"]["peer_executable"]["content_digest"] =
                    json!(digest_for(b"wrong executable"))
            },
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["peer_executable"]["byte_length"] = json!(4_097),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["runtime_state"] = json!("stopped"),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["restored_state_reconciled"] = json!(false),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["outcome"] = json!("mismatch"),
        ));
    }

    #[test]
    fn rejects_inconsistent_subject_resolution() {
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["subject_resolution"] = json!("index_member"),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| {
                response["measurement"]["resolved_image_manifest_digest"] =
                    json!(digest_for(b"unrelated manifest"))
            },
        ));
        assert_invalid(verify_mutation(OciSubjectKind::OciImageIndex, |response| {
            response["measurement"]["subject_resolution"] = json!("direct_manifest")
        }));

        let fixture = Fixture::new(OciSubjectKind::OciImageIndex);
        let subject_digest = fixture.oci_subject.content_digest.clone();
        let request = fixture.request();
        let response = fixture.response_with(&request, |response| {
            response["measurement"]["resolved_image_manifest_digest"] = json!(subject_digest);
        });
        assert_invalid(fixture.verify(request, &response));
    }

    #[test]
    fn rejects_counter_rollback_and_invalid_binding_digest() {
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["authority"]["authority_epoch"] = json!(6),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["authority"]["authority_revision"] = json!(0),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["sequence"] = json!(0),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| {
                response["measurement"]["workload_instance_binding_digest"] =
                    json!("sha256:invalid")
            },
        ));
    }

    #[test]
    fn enforces_exclusive_freshness_and_bounded_observation() {
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["valid_until"] = json!(instant(4)),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["observed_at"]["not_before"] = json!(instant(-1)),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["observed_at"]["not_after"] = json!(instant(4)),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["valid_until"] = json!(instant(302)),
        ));
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| response["measurement"]["observed_at"]["not_before"] = json!(instant(3)),
        ));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let response = fixture.response_with(&request, |_| {});
        let proof = fixture.verify(request, &response).expect("proof verifies");
        assert_invalid(proof.ensure_fresh(ConformanceTrustedTimeWindow {
            not_before: instant(239),
            not_after: instant(240),
        }));
        assert_invalid(proof.ensure_fresh(ConformanceTrustedTimeWindow {
            not_before: instant(1),
            not_after: instant(1),
        }));
    }

    #[test]
    fn rejects_unknown_duplicate_malformed_deep_and_oversized_json() {
        assert_invalid(verify_mutation(
            OciSubjectKind::OciImageManifest,
            |response| {
                response
                    .as_object_mut()
                    .expect("fixture object")
                    .insert("unexpected".to_owned(), json!(true));
            },
        ));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let valid = String::from_utf8(fixture.response_with(&request, |_| {}))
            .expect("fixture response is UTF-8");
        let duplicate = format!(
            "{{\"schema_version\":\"{}\",{}",
            DEPLOYED_WORKLOAD_PROTOCOL_VERSION,
            &valid[1..]
        );
        assert_invalid(fixture.verify(request, duplicate.as_bytes()));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let mut malformed: Value = serde_json::from_slice(&fixture.response_with(&request, |_| {}))
            .expect("fixture response parses");
        malformed["signature_base64"] = json!("not canonical base64");
        let malformed = serde_json::to_vec(&malformed).expect("malformed fixture serializes");
        assert_invalid(fixture.verify(request, &malformed));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        let mut deep = fixture.unsigned_response(&request);
        let mut nested = Value::Null;
        for _ in 0..=MAX_JSON_DEPTH {
            let mut object = Map::new();
            object.insert("next".to_owned(), nested);
            nested = Value::Object(object);
        }
        deep.as_object_mut()
            .expect("fixture object")
            .insert("nested".to_owned(), nested);
        let deep = serde_json::to_vec(&deep).expect("deep fixture serializes");
        assert_invalid(fixture.verify(request, &deep));

        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let request = fixture.request();
        assert_invalid(fixture.verify(
            request,
            &vec![b' '; MAX_DEPLOYED_WORKLOAD_RESPONSE_BYTES + 1],
        ));
    }

    #[test]
    fn request_and_authority_validation_fail_closed() {
        let fixture = Fixture::new(OciSubjectKind::OciImageManifest);
        let mut zero_nonce = test_entropy(b"zero nonce rejection");
        zero_nonce.fill(0);
        assert_invalid(build_deployed_workload_attestation_request(
            fixture.expected(),
            fixture.authority(),
            zero_nonce,
            instant(0),
        ));

        let mut invalid_expected = fixture.expected();
        let invalid_executable = RuntimeExecutable {
            content_digest: fixture.runtime_executable.content_digest.clone(),
            byte_length: 0,
        };
        invalid_expected.runtime_executable = &invalid_executable;
        assert_invalid(build_deployed_workload_attestation_request(
            invalid_expected,
            fixture.authority(),
            test_entropy(b"invalid executable request"),
            instant(0),
        ));

        let invalid_profile_digest = digest_for(b"substituted profile pin");
        let mut invalid_authority = fixture.authority();
        invalid_authority.measurement_profile_digest = &invalid_profile_digest;
        let request = fixture.request();
        let response = fixture.response_with(&request, |_| {});
        assert_invalid(verify_deployed_workload_attestation(
            request,
            &response,
            invalid_authority,
            trusted_time(),
        ));

        let request = fixture.request();
        let response = fixture.response_with(&request, |_| {});
        assert_invalid(verify_deployed_workload_attestation(
            request,
            &response,
            fixture.authority(),
            ConformanceTrustedTimeWindow {
                not_before: instant(4),
                not_after: instant(3),
            },
        ));
    }

    fn digest_from_response(response: &[u8], pointer: &str) -> String {
        serde_json::from_slice::<Value>(response)
            .expect("fixture response parses")
            .pointer(pointer)
            .and_then(Value::as_str)
            .expect("fixture digest is present")
            .to_owned()
    }
}
